/*
 * Source code generated by Celerio, a Jaxio product.
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Follow us on twitter: @jaxiosoft
 * Need commercial support ? Contact us: info@jaxio.com
 * Template pack-backend-jpa:src/test/java/service/ModelGenerator.e.vm.java
 * Template is part of Open Source Project: https://github.com/jaxio/pack-backend-jpa
 */
package com.jaxio.jsf2_spring_conversation_empty.repository;

import java.util.Date;

import javax.inject.Inject;
import javax.inject.Named;
import javax.inject.Singleton;

import com.jaxio.jsf2_spring_conversation_empty.domain.Absent;
import com.jaxio.jsf2_spring_conversation_empty.domain.Absentlog;
import com.jaxio.jsf2_spring_conversation_empty.domain.Employee;
import com.jaxio.jsf2_spring_conversation_empty.util.ValueGenerator;

/**
 * Helper class to create transient entities instance for testing purposes.
 * Simple properties are pre-filled with random values.
 */
@Named
@Singleton
public class AbsentlogGenerator {

    /**
     * Returns a new Absentlog instance filled with random values.
     */
    public Absentlog getAbsentlog() {
        Absentlog absentlog = new Absentlog();

        // primary key column must be set manually
        absentlog.setId(ValueGenerator.getUniqueInteger());
        // simple attributes follows
        absentlog.setLogdate(new Date());
        absentlog.setLogversionid(1);
        absentlog.setLognotes("a");
        // mandatory relation
        Employee employee = employeeGenerator.getEmployee();
        employeeRepository.save(employee);
        absentlog.setEmployee(employee);
        // mandatory relation
        Absent abs = absentGenerator.getAbsent();
        absentRepository.save(abs);
        absentlog.setAbs(abs);
        return absentlog;
    }

    @Inject
    private EmployeeRepository employeeRepository;
    @Inject
    private EmployeeGenerator employeeGenerator;
    @Inject
    private AbsentRepository absentRepository;
    @Inject
    private AbsentGenerator absentGenerator;
}