/*
 * Source code generated by Celerio, a Jaxio product.
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Follow us on twitter: @jaxiosoft
 * Need commercial support ? Contact us: info@jaxio.com
 * Template pack-backend-jpa:src/test/java/service/RepositoryIT.e.vm.java
 * Template is part of Open Source Project: https://github.com/jaxio/pack-backend-jpa
 */
package com.jaxio.jsf2_spring_conversation_empty.repository;

import static com.google.common.collect.Sets.newHashSet;
import static org.fest.assertions.Assertions.assertThat;

import java.util.Set;

import javax.inject.Inject;
import javax.persistence.EntityManager;
import javax.persistence.PersistenceContext;

import org.junit.Test;
import org.junit.runner.RunWith;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.test.annotation.Rollback;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

import com.jaxio.jsf2_spring_conversation_empty.domain.Absentlog;

/**
 * Integration test on AbsentlogRepository
 */
@RunWith(SpringJUnit4ClassRunner.class)
@ContextConfiguration(locations = { "classpath*:spring/applicationContext-test.xml" })
@Transactional
public class AbsentlogRepositoryIT {
    @SuppressWarnings("unused")
    private static final Logger log = LoggerFactory.getLogger(AbsentlogRepositoryIT.class);

    @PersistenceContext
    private EntityManager entityManager;

    @Inject
    private AbsentlogRepository absentlogRepository;

    @Inject
    private AbsentlogGenerator absentlogGenerator;

    @Test
    @Rollback
    public void saveAndGet() {
        Absentlog absentlog = absentlogGenerator.getAbsentlog();

        // add it to a Set before saving (force equals/hashcode)
        Set<Absentlog> set = newHashSet(absentlog, absentlog);
        assertThat(set).hasSize(1);

        absentlogRepository.save(absentlog);
        entityManager.flush();

        // reload it from cache and check equality
        Absentlog model = new Absentlog();
        model.setId(absentlog.getId());
        assertThat(absentlog).isEqualTo(absentlogRepository.get(model));

        // clear cache to force reload from db
        entityManager.clear();

        // since you use a business key, equality must be preserved.
        assertThat(absentlog).isEqualTo(absentlogRepository.get(model));
    }

}