/*
 * Source code generated by Celerio, a Jaxio product.
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Follow us on twitter: @jaxiosoft
 * Need commercial support ? Contact us: info@jaxio.com
 * Template pack-backend-jpa:src/test/java/service/ModelGenerator.e.vm.java
 * Template is part of Open Source Project: https://github.com/jaxio/pack-backend-jpa
 */
package com.jaxio.jsf2_spring_conversation_empty.repository;

import java.util.Date;

import javax.inject.Inject;
import javax.inject.Named;
import javax.inject.Singleton;

import com.jaxio.jsf2_spring_conversation_empty.domain.Absent;
import com.jaxio.jsf2_spring_conversation_empty.domain.Employee;
import com.jaxio.jsf2_spring_conversation_empty.util.ValueGenerator;

/**
 * Helper class to create transient entities instance for testing purposes.
 * Simple properties are pre-filled with random values.
 */
@Named
@Singleton
public class AbsentGenerator {

    /**
     * Returns a new Absent instance filled with random values.
     */
    public Absent getAbsent() {
        Absent absent = new Absent();

        // primary key column must be set manually
        absent.setId(ValueGenerator.getUniqueInteger());
        // simple attributes follows
        absent.setAbsdate(new Date());
        absent.setAbstype("a");
        absent.setAbsnotes("a");
        absent.setAbsdeleted(true);
        // mandatory relation
        Employee emp = employeeGenerator.getEmployee();
        employeeRepository.save(emp);
        absent.setEmp(emp);
        return absent;
    }

    @Inject
    private EmployeeRepository employeeRepository;
    @Inject
    private EmployeeGenerator employeeGenerator;
}