/*
 * Source code generated by Celerio, a Jaxio product.
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Follow us on twitter: @jaxiosoft
 * Need commercial support ? Contact us: info@jaxio.com
 * Template pack-backend-jpa:src/test/java/service/ModelGenerator.e.vm.java
 * Template is part of Open Source Project: https://github.com/jaxio/pack-backend-jpa
 */
package com.jaxio.jsf2_spring_conversation_empty.repository;

import javax.inject.Named;
import javax.inject.Singleton;

import com.jaxio.jsf2_spring_conversation_empty.domain.Employee;
import com.jaxio.jsf2_spring_conversation_empty.util.ValueGenerator;

/**
 * Helper class to create transient entities instance for testing purposes.
 * Simple properties are pre-filled with random values.
 */
@Named
@Singleton
public class EmployeeGenerator {

    /**
     * Returns a new Employee instance filled with random values.
     */
    public Employee getEmployee() {
        Employee employee = new Employee();

        // primary key column must be set manually
        employee.setId(ValueGenerator.getUniqueInteger());
        // simple attributes follows
        employee.setEmpuhnumber("a");
        employee.setEmpfirstname("a");
        employee.setEmplastname("a");
        employee.setEmprole("a");
        employee.setEmpdivision("a");
        employee.setEmpstatus("a");
        return employee;
    }

}