/*
 * Source code generated by Celerio, a Jaxio product.
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Follow us on twitter: @jaxiosoft
 * Need commercial support ? Contact us: info@jaxio.com
 * Template pack-backend-jpa:src/main/java/printer/Printer.e.vm.java
 * Template is part of Open Source Project: https://github.com/jaxio/pack-backend-jpa
 */
package com.jaxio.backend_jpa_bank.printer;

import java.util.Locale;

import javax.inject.Named;
import javax.inject.Singleton;

import com.jaxio.backend_jpa_bank.domain.Currency;
import com.jaxio.backend_jpa_bank.domain.Currency_;
import com.jaxio.backend_jpa_bank.printer.support.GenericPrinter;

/**
 * {@link GenericPrinter} for {@link Currency} 
 *
 * @see GenericPrinter
 * @see TypeAwarePrinter
 */
@Named
@Singleton
public class CurrencyPrinter extends GenericPrinter<Currency> {
    public CurrencyPrinter() {
        super(Currency.class, Currency_.name);
    }

    @Override
    public String print(Currency currency, Locale locale) {
        if (currency == null) {
            return "";
        }
        StringBuilder ret = new StringBuilder();
        appendIfNotEmpty(ret, currency.getName());
        return ret.toString();
    }
}