/*
 * Source code generated by Celerio, a Jaxio product.
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Follow us on twitter: @jaxiosoft
 * Need commercial support ? Contact us: info@jaxio.com
 * Template pack-backend-jpa:src/main/java/printer/Printer.e.vm.java
 * Template is part of Open Source Project: https://github.com/jaxio/pack-backend-jpa
 */
package com.jaxio.backend_jpa_bank.printer;

import java.util.Locale;

import javax.inject.Named;
import javax.inject.Singleton;

import com.jaxio.backend_jpa_bank.domain.Customer;
import com.jaxio.backend_jpa_bank.domain.Customer_;
import com.jaxio.backend_jpa_bank.printer.support.GenericPrinter;

/**
 * {@link GenericPrinter} for {@link Customer} 
 *
 * @see GenericPrinter
 * @see TypeAwarePrinter
 */
@Named
@Singleton
public class CustomerPrinter extends GenericPrinter<Customer> {
    public CustomerPrinter() {
        super(Customer.class, Customer_.companyName);
    }

    @Override
    public String print(Customer customer, Locale locale) {
        if (customer == null) {
            return "";
        }
        StringBuilder ret = new StringBuilder();
        appendIfNotEmpty(ret, customer.getCompanyName());
        return ret.toString();
    }
}