/*
 * Source code generated by Celerio, a Jaxio product.
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Follow us on twitter: @jaxiosoft
 * Need commercial support ? Contact us: info@jaxio.com
 * Template pack-javaee7-backend:src/test/java/service/ModelGenerator.e.vm.java
 * Template is part of Open Source Project: https://github.com/jaxio/javaee-lab
 */
package com.jaxio.javaee7_wildfly_bank.repository;

import java.math.BigDecimal;
import java.util.Date;

import javax.inject.Inject;
import javax.inject.Named;
import javax.inject.Singleton;

import com.jaxio.javaee7_wildfly_bank.domain.Account;
import com.jaxio.javaee7_wildfly_bank.domain.Currency;
import com.jaxio.javaee7_wildfly_bank.domain.Transaction;

/**
 * Helper class to create transient entities instance for testing purposes.
 * Simple properties are pre-filled with random values.
 */
@Named
@Singleton
public class TransactionGenerator {

    /**
     * Returns a new Transaction instance filled with random values.
     */
    public Transaction getTransaction() {
        Transaction transaction = new Transaction();

        // simple attributes follows
        transaction.setAmount(BigDecimal.ONE);
        transaction.setTransactionDate(new Date());
        transaction.setValueDate(new Date());
        transaction.setDescription("a");
        // mandatory relation
        Currency currency = currencyGenerator.getCurrency();
        currencyRepository.save(currency);
        transaction.setCurrency(currency);
        // mandatory relation
        Account account = accountGenerator.getAccount();
        accountRepository.save(account);
        transaction.setAccount(account);
        return transaction;
    }

    @Inject
    private CurrencyRepository currencyRepository;
    @Inject
    private CurrencyGenerator currencyGenerator;
    @Inject
    private AccountRepository accountRepository;
    @Inject
    private AccountGenerator accountGenerator;
}