/*
 * Source code generated by Celerio, a Jaxio product.
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Follow us on twitter: @jaxiosoft
 * Need commercial support ? Contact us: info@jaxio.com
 * Template pack-backend-jpa:src/main/java/printer/Printer.e.vm.java
 * Template is part of Open Source Project: https://github.com/jaxio/pack-backend-jpa
 */
package com.jaxio.jsf2_spring_conversation_empty.printer;

import java.util.Locale;

import javax.inject.Named;
import javax.inject.Singleton;

import com.jaxio.jsf2_spring_conversation_empty.domain.Absentlog;
import com.jaxio.jsf2_spring_conversation_empty.domain.Absentlog_;
import com.jaxio.jsf2_spring_conversation_empty.printer.support.GenericPrinter;

/**
 * {@link GenericPrinter} for {@link Absentlog} 
 *
 * @see GenericPrinter
 * @see TypeAwarePrinter
 */
@Named
@Singleton
public class AbsentlogPrinter extends GenericPrinter<Absentlog> {
    public AbsentlogPrinter() {
        super(Absentlog.class, Absentlog_.lognotes);
    }

    @Override
    public String print(Absentlog absentlog, Locale locale) {
        if (absentlog == null) {
            return "";
        }
        StringBuilder ret = new StringBuilder();
        appendIfNotEmpty(ret, absentlog.getLognotes());
        return ret.toString();
    }
}