/*
 * Source code generated by Celerio, a Jaxio product.
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Follow us on twitter: @jaxiosoft
 * Need commercial support ? Contact us: info@jaxio.com
 * Template pack-backend-jpa:src/main/java/printer/Printer.e.vm.java
 * Template is part of Open Source Project: https://github.com/jaxio/pack-backend-jpa
 */
package com.jaxio.jsf2_spring_conversation_empty.printer;

import java.util.Locale;

import javax.inject.Named;
import javax.inject.Singleton;

import com.jaxio.jsf2_spring_conversation_empty.domain.Empmanager;
import com.jaxio.jsf2_spring_conversation_empty.domain.Empmanager_;
import com.jaxio.jsf2_spring_conversation_empty.printer.support.GenericPrinter;

/**
 * {@link GenericPrinter} for {@link Empmanager} 
 *
 * @see GenericPrinter
 * @see TypeAwarePrinter
 */
@Named
@Singleton
public class EmpmanagerPrinter extends GenericPrinter<Empmanager> {
    public EmpmanagerPrinter() {
        super(Empmanager.class, Empmanager_.division);
    }

    @Override
    public String print(Empmanager empmanager, Locale locale) {
        if (empmanager == null) {
            return "";
        }
        StringBuilder ret = new StringBuilder();
        appendIfNotEmpty(ret, empmanager.getDivision());
        return ret.toString();
    }
}