/*
 * Source code generated by Celerio, a Jaxio product.
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Follow us on twitter: @jaxiosoft
 * Need commercial support ? Contact us: info@jaxio.com
 * Template pack-jsf2-spring-conversation:src/main/java/domain/support/CommonAction.p.vm.java
 * Template is part of Open Source Project: https://github.com/jaxio/pack-jsf2-spring-conversation
 */
package com.jaxio.jsf2_spring_conversation_empty.web.domain.support;

import static com.jaxio.jsf2_spring_conversation_empty.web.conversation.ConversationHolder.getCurrentConversation;

import com.jaxio.jsf2_spring_conversation_empty.web.conversation.ConversationContext;
import com.jaxio.jsf2_spring_conversation_empty.web.conversation.ConversationManager;

/**
 * Simple actions that can be shared.
 */
public abstract class CommonAction<E> {

    /**
     * Back action is used from readonly page to go back. It is expected to be non-ajax.
     */
    public String back() {
        return context().getCallBack().back();
    }

    /**
     * Ends the current conversation. It is expected to be non-ajax.
     */
    public String quit() {
        ConversationManager.getInstance().endCurrentConversation();
        return "/home.faces?faces-redirect=true"; // TODO: clean url, referer or else
    }

    /**
     * Returns the current {@link ConversationContext}.
     */
    public ConversationContext<E> context() {
        return getCurrentConversation().getCurrentContext();
    }
}