/*
 * Source code generated by Celerio, a Jaxio product.
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Follow us on twitter: @jaxiosoft
 * Need commercial support ? Contact us: info@jaxio.com
 * Template pack-jsf2-spring-conversation:src/main/java/domain/support/SavedSearchService.p.vm.java
 * Template is part of Open Source Project: https://github.com/jaxio/pack-jsf2-spring-conversation
 */
package com.jaxio.jsf2_spring_conversation_bank.web.domain.support;

import static com.google.common.collect.Lists.newArrayList;

import java.util.List;

import javax.inject.Inject;
import javax.inject.Named;
import javax.inject.Singleton;

import org.springframework.transaction.annotation.Transactional;

import com.jaxio.jpa.querybyexample.SearchParameters;
import com.jaxio.jsf2_spring_conversation_bank.context.UserContext;
import com.jaxio.jsf2_spring_conversation_bank.domain.SavedSearch;
import com.jaxio.jsf2_spring_conversation_bank.domain.SavedSearch_;
import com.jaxio.jsf2_spring_conversation_bank.domain.User;
import com.jaxio.jsf2_spring_conversation_bank.repository.SavedSearchRepository;
import com.jaxio.jsf2_spring_conversation_bank.repository.UserRepository;
import com.jaxio.jsf2_spring_conversation_bank.web.util.MessageUtil;

/**
 * Store/Load Search Form Content to db.
 */
@Named
@Singleton
@SuppressWarnings({ "rawtypes" })
public class SavedSearchService {
    @Inject
    private SavedSearchRepository savedSearchRepository;
    @Inject
    private MessageUtil messageUtil;
    @Inject
    private UserRepository userRepository;

    @Transactional
    public void save(GenericSearchForm searchForm) {
        SavedSearch savedSearch = savedSearchRepository.findUniqueOrNone(example(searchForm));

        if (savedSearch == null) {
            savedSearch = example(searchForm);
        }

        if (searchForm.isPrivateSearch()) {
            savedSearch = markSearchPrivate(savedSearch);
        } else {
            savedSearch = markSearchPublic(savedSearch);
        }

        savedSearch.setFormContent(searchForm.toByteArray());
        savedSearchRepository.save(savedSearch);
        messageUtil.info("saved_search_saved", savedSearch.getName());

        // manual search form reset : reset only form metadata 
        searchForm.setSearchFormName(null);
        searchForm.setPrivateSearch(false);
    }

    private SavedSearch example(GenericSearchForm searchForm) {
        SavedSearch savedSearch = new SavedSearch();
        savedSearch.setName(searchForm.getSearchFormName());
        savedSearch.setFormClassname(searchForm.getClass().getSimpleName());
        return savedSearch;
    }

    /**
     * @param savedSearch
     * @return savedSearch marked as private with current user
     */
    private SavedSearch markSearchPrivate(SavedSearch savedSearch) {
        User currentUser = userRepository.getById(UserContext.getId());
        savedSearch.setUser(currentUser);
        return savedSearch;
    }

    private SavedSearch markSearchPublic(SavedSearch savedSearch) {
        return savedSearch.user(null);
    }

    private SavedSearch privateExample(GenericSearchForm searchForm) {
        return markSearchPrivate(example(searchForm));
    }

    public <F extends GenericSearchForm> Finder finderFor(F searchFrom) {
        // we use a Finder in order to have the required List<String> find(String) method
        return new Finder(savedSearchRepository, searchFrom);
    }

    public class Finder {
        private SavedSearchRepository savedSearchRepository;
        private GenericSearchForm searchFrom;

        public Finder(SavedSearchRepository savedSearchRepository, GenericSearchForm searchFrom) {
            this.savedSearchRepository = savedSearchRepository;
            this.searchFrom = searchFrom;
        }

        public List<SavedSearch> find(String name) {
            List<SavedSearch> searches = newArrayList();
            searches.addAll(findPrivate(name));
            searches.addAll(findPublic(name));
            return searches;
        }

        private List<SavedSearch> findPublic(String name) {
            List<SavedSearch> results = newArrayList();
            SavedSearch example = example(searchFrom).name(name);
            SearchParameters sp = new SearchParameters() //
                    .caseInsensitive() //
                    .anywhere() //
                    .property(SavedSearch_.user, (Object) null);
            for (SavedSearch savedSearch : savedSearchRepository.find(example, sp)) {
                results.add(savedSearch);
            }
            return results;
        }

        private List<SavedSearch> findPrivate(String name) {
            List<SavedSearch> results = newArrayList();
            SavedSearch example = privateExample(searchFrom).name(name);
            SearchParameters anywhere = new SearchParameters() //
                    .caseInsensitive() //
                    .anywhere();
            for (SavedSearch savedSearch : savedSearchRepository.find(example, anywhere)) {
                results.add(savedSearch);
            }
            return results;
        }
    }
}