/*
 * Source code generated by Celerio, a Jaxio product.
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Follow us on twitter: @jaxiosoft
 * Need commercial support ? Contact us: info@jaxio.com
 * Template pack-javaee7-frontend:src/main/java/services/UserContextService.p.vm.java
 * Template is part of Open Source Project: https://github.com/jaxio/javaee-lab
 */
package com.jaxio.javaee7_wildfly_bank.web.service;

import static com.google.common.collect.Lists.newArrayList;

import java.util.List;

import javax.enterprise.context.ApplicationScoped;
import javax.inject.Named;

import com.jaxio.javaee7_wildfly_bank.context.UserContext;

/**
 * Simple pass over to access static 'userContext' from EL.
 */
@ApplicationScoped
@Named
public class UserContextService {
    public String getUsername() {
        return UserContext.getUsername();
    }

    public boolean isAnonymousUser() {
        return UserContext.ANONYMOUS_USER.equalsIgnoreCase(getUsername());
    }

    public boolean isLoggedIn() {
        return !isAnonymousUser();
    }

    // TODO: improve... 
    public List<String> getRoles() {
        List<String> roles = newArrayList();

        if (hasRole("ROLE_ADMIN")) {
            roles.add("ROLE_ADMIN");
        }

        if (hasRole("ROLE_USER")) {
            roles.add("ROLE_USER");
        }

        if (hasRole("ROLE_MONITORING")) {
            roles.add("ROLE_MONITORING");
        }

        return roles;
    }

    public boolean hasRole(String role) {
        return UserContext.hasRole(role);
    }
}