/*
 * Source code generated by Celerio, a Jaxio product.
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Follow us on twitter: @jaxiosoft
 * Need commercial support ? Contact us: info@jaxio.com
 * Template pack-backend-jpa:src/test/java/domain/ModelTest.e.vm.java
 * Template is part of Open Source Project: https://github.com/jaxio/pack-backend-jpa
 */
package com.jaxio.jsf2_spring_conversation_empty.domain;

import static org.fest.assertions.Assertions.assertThat;

import java.io.*;
import java.util.*;

import org.junit.Test;

import com.jaxio.jsf2_spring_conversation_empty.util.ValueGenerator;

/**
 * Basic tests for Employee
 */
@SuppressWarnings("unused")
public class EmployeeTest {

    // test unique primary key
    @Test
    public void newInstanceHasNoPrimaryKey() {
        Employee model = new Employee();
        assertThat(model.isIdSet()).isFalse();
    }

    @Test
    public void isIdSetReturnsTrue() {
        Employee model = new Employee();
        model.setId(ValueGenerator.getUniqueInteger());
        assertThat(model.getId()).isNotNull();
        assertThat(model.isIdSet()).isTrue();
    }

    /*
     public void equalsUsingPk() {
     Employee model1 = new Employee();
     Employee model2 = new Employee();

     Integer id = ValueGenerator.getUniqueInteger();
     model1.setId(id);
     model2.setId(id);

     model1.setEmpuhnumber("a");
     model2.setEmpuhnumber("a");

     model1.setEmpfirstname("a");
     model2.setEmpfirstname("a");

     model1.setEmplastname("a");
     model2.setEmplastname("a");

     model1.setEmprole("a");
     model2.setEmprole("a");

     model1.setEmpdivision("a");
     model2.setEmpdivision("a");

     model1.setEmpstatus("a");
     model2.setEmpstatus("a");
     assertThat(model1.isIdSet()).isTrue();
     assertThat(model2.isIdSet()).isTrue();
     assertThat(model1.hashCode()).isEqualTo(model2.hashCode());
     assertThat(model1).isEqualTo(model2);
     assertThat(model2).isEqualTo(model1);
     }
     */
}