/*
 * Source code generated by Celerio, a Jaxio product.
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Follow us on twitter: @jaxiosoft
 * Need commercial support ? Contact us: info@jaxio.com
 * Template pack-backend-jpa:src/test/java/service/RepositoryIT.e.vm.java
 * Template is part of Open Source Project: https://github.com/jaxio/pack-backend-jpa
 */
package com.jaxio.backend_jpa_bank.repository;

import static com.google.common.collect.Sets.newHashSet;
import static org.fest.assertions.Assertions.assertThat;

import java.util.List;
import java.util.Set;

import javax.inject.Inject;
import javax.persistence.EntityManager;
import javax.persistence.PersistenceContext;

import org.junit.Test;
import org.junit.runner.RunWith;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.test.annotation.Rollback;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

import com.jaxio.backend_jpa_bank.domain.Customer;
import com.jaxio.backend_jpa_bank.domain.Customer_;
import com.jaxio.jpa.querybyexample.SearchParameters;

/**
 * Integration test on CustomerRepository
 */
@RunWith(SpringJUnit4ClassRunner.class)
@ContextConfiguration(locations = { "classpath*:spring/applicationContext-test.xml" })
@Transactional
public class CustomerRepositoryIT {
    @SuppressWarnings("unused")
    private static final Logger log = LoggerFactory.getLogger(CustomerRepositoryIT.class);

    @PersistenceContext
    private EntityManager entityManager;

    @Inject
    private CustomerRepository customerRepository;

    @Inject
    private CustomerGenerator customerGenerator;

    @Test
    @Rollback
    public void saveAndGet() {
        Customer customer = customerGenerator.getCustomer();

        // add it to a Set before saving (force equals/hashcode)
        Set<Customer> set = newHashSet(customer, customer);
        assertThat(set).hasSize(1);

        customerRepository.save(customer);
        entityManager.flush();

        // reload it from cache and check equality
        Customer model = new Customer();
        model.setId(customer.getId());
        assertThat(customer).isEqualTo(customerRepository.get(model));

        // clear cache to force reload from db
        entityManager.clear();

        // pk are equals...
        assertThat(customer.getId()).isEqualTo(customerRepository.get(model).getId());

        // but since you do not use a business key, equality is lost.
        assertThat(customer).isNotEqualTo(customerRepository.get(model));
    }

    @Test
    @Rollback
    public void saveAndGetWithExplicitNullPropertySelector() {
        Customer customer = customerGenerator.getCustomer();

        // add it to a Set before saving (force equals/hashcode)
        Set<Customer> set = newHashSet(customer, customer);
        assertThat(set).hasSize(1);

        // explicitly set toOne relationship to null
        customer.setAddress(null);

        customerRepository.save(customer);
        entityManager.flush();

        // clear cache to force reload from db
        entityManager.clear();

        SearchParameters searchParameters = new SearchParameters() //
                .caseInsensitive() //
                .anywhere() //
                .property(Customer_.address, (Object) null);

        List<Customer> elements = customerRepository.find(searchParameters);
        assertThat(elements).isNotEmpty();
        for (Customer element : elements) {
            assertThat(element.getAddress()).isNull();
        }
    }
}