/*
 * Source code generated by Celerio, a Jaxio product.
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Follow us on twitter: @jaxiosoft
 * Need commercial support ? Contact us: info@jaxio.com
 * Template pack-backend-jpa:src/main/java/repository/Repository.e.vm.java
 * Template is part of Open Source Project: https://github.com/jaxio/pack-backend-jpa
 */
package com.jaxio.jsf2_spring_conversation_bank.repository;

import javax.inject.Named;
import javax.inject.Singleton;

import com.jaxio.jpa.querybyexample.GenericRepository;
import com.jaxio.jsf2_spring_conversation_bank.domain.Address;

/**
 * {@link GenericRepository} for {@link Address} 
 */
@Named
@Singleton
public class AddressRepository extends GenericRepository<Address, Integer> {

    public AddressRepository() {
        super(Address.class);
    }

    @Override
    public Address getNew() {
        return new Address();
    }

    @Override
    public Address getNewWithDefaults() {
        return getNew().withDefaults();
    }
}