/*
 * Source code generated by Celerio, a Jaxio product.
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Follow us on twitter: @jaxiosoft
 * Need commercial support ? Contact us: info@jaxio.com
 * Template pack-jsf2-spring-conversation:src/main/java/domain/Controller.e.vm.java
 * Template is part of Open Source Project: https://github.com/jaxio/pack-jsf2-spring-conversation
 */
package com.jaxio.jsf2_spring_conversation_empty.web.domain;

import javax.inject.Inject;
import javax.inject.Named;
import javax.inject.Singleton;

import com.jaxio.jsf2_spring_conversation_empty.domain.Absent;
import com.jaxio.jsf2_spring_conversation_empty.printer.AbsentPrinter;
import com.jaxio.jsf2_spring_conversation_empty.repository.AbsentRepository;
import com.jaxio.jsf2_spring_conversation_empty.web.domain.support.GenericController;
import com.jaxio.jsf2_spring_conversation_empty.web.permission.AbsentPermission;

/**
 * Stateless controller for {@link Absent} conversation start.
 */
@Named
@Singleton
public class AbsentController extends GenericController<Absent, Integer> {
    public static final String ABSENT_EDIT_URI = "/domain/absentEdit.faces";
    public static final String ABSENT_SELECT_URI = "/domain/absentSelect.faces";

    @Inject
    public AbsentController(AbsentRepository absentRepository, AbsentPermission absentPermission, AbsentPrinter absentPrinter) {
        super(absentRepository, absentPermission, absentPrinter, ABSENT_SELECT_URI, ABSENT_EDIT_URI);
    }
}