/*
 * Source code generated by Celerio, a Jaxio product.
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Follow us on twitter: @jaxiosoft
 * Need commercial support ? Contact us: info@jaxio.com
 * Template pack-jsf2-spring-conversation:src/main/java/domain/EditForm.e.vm.java
 * Template is part of Open Source Project: https://github.com/jaxio/pack-jsf2-spring-conversation
 */
package com.jaxio.jsf2_spring_conversation_empty.web.domain;

import javax.annotation.PostConstruct;
import javax.inject.Inject;
import javax.inject.Named;
import javax.validation.constraints.NotNull;

import com.jaxio.jsf2_spring_conversation_empty.domain.Absent;
import com.jaxio.jsf2_spring_conversation_empty.domain.Absentlog;
import com.jaxio.jsf2_spring_conversation_empty.domain.Absentlog_;
import com.jaxio.jsf2_spring_conversation_empty.domain.Employee;
import com.jaxio.jsf2_spring_conversation_empty.repository.AbsentlogRepository;
import com.jaxio.jsf2_spring_conversation_empty.web.domain.support.GenericEditForm;
import com.jaxio.jsf2_spring_conversation_empty.web.domain.support.GenericToOneAssociation;
import com.jaxio.jsf2_spring_conversation_empty.web.faces.ConversationContextScoped;

/**
 * View Helper/Controller to edit {@link Absentlog}.
 */
@Named
@ConversationContextScoped
public class AbsentlogEditForm extends GenericEditForm<Absentlog, Integer> {
    @Inject
    protected AbsentlogController absentlogController;
    @Inject
    protected EmployeeController employeeController;
    protected GenericToOneAssociation<Employee, Integer> employee;
    @Inject
    protected AbsentController absentController;
    protected GenericToOneAssociation<Absent, Integer> abs;

    @Inject
    public AbsentlogEditForm(AbsentlogRepository absentlogRepository, AbsentlogGraphLoader absentlogGraphLoader) {
        super(absentlogRepository, absentlogGraphLoader);
    }

    /**
     * The entity to edit/view.
     */
    public Absentlog getAbsentlog() {
        return getEntity();
    }

    public String print() {
        return absentlogController.print(getAbsentlog());
    }

    @PostConstruct
    void setupEmployeeActions() {
        employee = new GenericToOneAssociation<Employee, Integer>(employeeController, Absentlog_.employee) {
            @Override
            protected Employee get() {
                return getAbsentlog().getEmployee();
            }

            @Override
            protected void set(Employee employee) {
                getAbsentlog().setEmployee(employee);
            }

            @NotNull
            @Override
            public Employee getSelected() {
                return super.getSelected();
            }
        };
    }

    public GenericToOneAssociation<Employee, Integer> getEmployee() {
        return employee;
    }

    @PostConstruct
    void setupAbsActions() {
        abs = new GenericToOneAssociation<Absent, Integer>(absentController, Absentlog_.abs) {
            @Override
            protected Absent get() {
                return getAbsentlog().getAbs();
            }

            @Override
            protected void set(Absent absent) {
                getAbsentlog().setAbs(absent);
            }

            @NotNull
            @Override
            public Absent getSelected() {
                return super.getSelected();
            }
        };
    }

    public GenericToOneAssociation<Absent, Integer> getAbs() {
        return abs;
    }
}
