/*
 * Source code generated by Celerio, a Jaxio product.
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Follow us on twitter: @jaxiosoft
 * Need commercial support ? Contact us: info@jaxio.com
 * Template pack-jsf2-spring-conversation:src/main/java/domain/Controller.e.vm.java
 * Template is part of Open Source Project: https://github.com/jaxio/pack-jsf2-spring-conversation
 */
package com.jaxio.jsf2_spring_conversation_empty.web.domain;

import javax.inject.Inject;
import javax.inject.Named;
import javax.inject.Singleton;

import com.jaxio.jsf2_spring_conversation_empty.domain.Absentlog;
import com.jaxio.jsf2_spring_conversation_empty.printer.AbsentlogPrinter;
import com.jaxio.jsf2_spring_conversation_empty.repository.AbsentlogRepository;
import com.jaxio.jsf2_spring_conversation_empty.web.domain.support.GenericController;
import com.jaxio.jsf2_spring_conversation_empty.web.permission.AbsentlogPermission;

/**
 * Stateless controller for {@link Absentlog} conversation start.
 */
@Named
@Singleton
public class AbsentlogController extends GenericController<Absentlog, Integer> {
    public static final String ABSENTLOG_EDIT_URI = "/domain/absentlogEdit.faces";
    public static final String ABSENTLOG_SELECT_URI = "/domain/absentlogSelect.faces";

    @Inject
    public AbsentlogController(AbsentlogRepository absentlogRepository, AbsentlogPermission absentlogPermission, AbsentlogPrinter absentlogPrinter) {
        super(absentlogRepository, absentlogPermission, absentlogPrinter, ABSENTLOG_SELECT_URI, ABSENTLOG_EDIT_URI);
    }
}