/*
 * Source code generated by Celerio, a Jaxio product.
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Follow us on twitter: @jaxiosoft
 * Need commercial support ? Contact us: info@jaxio.com
 * Template pack-jsf2-spring-conversation:src/main/java/domain/EditForm.e.vm.java
 * Template is part of Open Source Project: https://github.com/jaxio/pack-jsf2-spring-conversation
 */
package com.jaxio.jsf2_spring_conversation_empty.web.domain;

import javax.annotation.PostConstruct;
import javax.inject.Inject;
import javax.inject.Named;
import javax.validation.constraints.NotNull;

import com.jaxio.jsf2_spring_conversation_empty.domain.Absent;
import com.jaxio.jsf2_spring_conversation_empty.domain.Absent_;
import com.jaxio.jsf2_spring_conversation_empty.domain.Employee;
import com.jaxio.jsf2_spring_conversation_empty.repository.AbsentRepository;
import com.jaxio.jsf2_spring_conversation_empty.web.domain.support.GenericEditForm;
import com.jaxio.jsf2_spring_conversation_empty.web.domain.support.GenericToOneAssociation;
import com.jaxio.jsf2_spring_conversation_empty.web.faces.ConversationContextScoped;

/**
 * View Helper/Controller to edit {@link Absent}.
 */
@Named
@ConversationContextScoped
public class AbsentEditForm extends GenericEditForm<Absent, Integer> {
    @Inject
    protected AbsentController absentController;
    @Inject
    protected EmployeeController employeeController;
    protected GenericToOneAssociation<Employee, Integer> emp;

    @Inject
    public AbsentEditForm(AbsentRepository absentRepository, AbsentGraphLoader absentGraphLoader) {
        super(absentRepository, absentGraphLoader);
    }

    /**
     * The entity to edit/view.
     */
    public Absent getAbsent() {
        return getEntity();
    }

    public String print() {
        return absentController.print(getAbsent());
    }

    @PostConstruct
    void setupEmpActions() {
        emp = new GenericToOneAssociation<Employee, Integer>(employeeController, Absent_.emp) {
            @Override
            protected Employee get() {
                return getAbsent().getEmp();
            }

            @Override
            protected void set(Employee employee) {
                getAbsent().setEmp(employee);
            }

            @NotNull
            @Override
            public Employee getSelected() {
                return super.getSelected();
            }
        };
    }

    public GenericToOneAssociation<Employee, Integer> getEmp() {
        return emp;
    }
}
