/*
 * Source code generated by Celerio, a Jaxio product.
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Follow us on twitter: @jaxiosoft
 * Need commercial support ? Contact us: info@jaxio.com
 * Template pack-jsf2-spring-conversation:src/main/java/domain/LazyDataModel.e.vm.java
 * Template is part of Open Source Project: https://github.com/jaxio/pack-jsf2-spring-conversation
 */
package com.jaxio.jsf2_spring_conversation_empty.web.domain;

import javax.inject.Inject;
import javax.inject.Named;

import org.primefaces.model.LazyDataModel;

import com.jaxio.jsf2_spring_conversation_empty.domain.Absentlog;
import com.jaxio.jsf2_spring_conversation_empty.repository.AbsentlogRepository;
import com.jaxio.jsf2_spring_conversation_empty.web.domain.support.GenericLazyDataModel;
import com.jaxio.jsf2_spring_conversation_empty.web.faces.ConversationContextScoped;

/**
 * Provide PrimeFaces {@link LazyDataModel} for {@link Absentlog}
 */
@Named
@ConversationContextScoped
public class AbsentlogLazyDataModel extends GenericLazyDataModel<Absentlog, Integer, AbsentlogSearchForm> {
    private static final long serialVersionUID = 1L;

    @Inject
    public AbsentlogLazyDataModel(AbsentlogRepository absentlogRepository, AbsentlogController absentlogController, AbsentlogSearchForm absentlogSearchForm,
            AbsentlogExcelExporter absentlogExcelExporter) {
        super(absentlogRepository, absentlogController, absentlogSearchForm, absentlogExcelExporter);
    }
}