/*
 * Source code generated by Celerio, a Jaxio product.
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Follow us on twitter: @jaxiosoft
 * Need commercial support ? Contact us: info@jaxio.com
 * Template pack-jsf2-spring-conversation:src/main/java/domain/ExcelExporter.e.vm.java
 * Template is part of Open Source Project: https://github.com/jaxio/pack-jsf2-spring-conversation
 */
package com.jaxio.jsf2_spring_conversation_empty.web.domain;

import javax.inject.Inject;
import javax.inject.Named;

import com.jaxio.jsf2_spring_conversation_empty.domain.Absent;
import com.jaxio.jsf2_spring_conversation_empty.web.domain.support.GenericExcelExporter;
import com.jaxio.jsf2_spring_conversation_empty.web.faces.ConversationContextScoped;

/**
 * Exports to excel document {@link Absent} search criteria and result. 
 */
@Named
@ConversationContextScoped
public class AbsentExcelExporter extends GenericExcelExporter<Absent> {
    @Inject
    protected AbsentSearchForm sf;

    public AbsentExcelExporter() {
        super("absent_id", "absent_absdate", "absent_abstype", "absent_absnotes", "absent_absdeleted");
    }

    @Override
    protected void fillResultItem(int row, Absent item) {
        int col = 0;
        setValue(row, col++, item.getId());
        setDateTime(row, col++, item.getAbsdate());
        setValue(row, col++, item.getAbstype());
        setValue(row, col++, item.getAbsnotes());
        setValue(row, col++, item.getAbsdeleted());
    }

    @Override
    public void fillSearchCriteria(int row) {
        useCriteriaSheet();

        setSelectedEntities(row++, 0, "absent_emp", sf.getEmpSelector().getSelected());
        setLeftHeader(row, 0, "absent_id");
        setValue(row++, 1, sf.getAbsent().getId());
        setRangeDateTime(row++, 0, "absent_absdate", sf.getAbsdateRange());
        setSelector(row++, 0, "absent_abstype", sf.getAbstypeSelector());
        setSelector(row++, 0, "absent_absnotes", sf.getAbsnotesSelector());
        setSelector(row++, 0, "absent_absdeleted", sf.getAbsdeletedSelector());
    }
}