/*
 * Source code generated by Celerio, a Jaxio product.
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Follow us on twitter: @jaxiosoft
 * Need commercial support ? Contact us: info@jaxio.com
 * Template pack-jsf2-spring-conversation:src/main/java/domain/ExcelExporter.e.vm.java
 * Template is part of Open Source Project: https://github.com/jaxio/pack-jsf2-spring-conversation
 */
package com.jaxio.jsf2_spring_conversation_empty.web.domain;

import javax.inject.Inject;
import javax.inject.Named;

import com.jaxio.jsf2_spring_conversation_empty.domain.Employee;
import com.jaxio.jsf2_spring_conversation_empty.web.domain.support.GenericExcelExporter;
import com.jaxio.jsf2_spring_conversation_empty.web.faces.ConversationContextScoped;

/**
 * Exports to excel document {@link Employee} search criteria and result. 
 */
@Named
@ConversationContextScoped
public class EmployeeExcelExporter extends GenericExcelExporter<Employee> {
    @Inject
    protected EmployeeSearchForm sf;

    public EmployeeExcelExporter() {
        super("employee_id", "employee_empuhnumber", "employee_empfirstname", "employee_emplastname", "employee_emprole", "employee_empdivision");
    }

    @Override
    protected void fillResultItem(int row, Employee item) {
        int col = 0;
        setValue(row, col++, item.getId());
        setValue(row, col++, item.getEmpuhnumber());
        setValue(row, col++, item.getEmpfirstname());
        setValue(row, col++, item.getEmplastname());
        setValue(row, col++, item.getEmprole());
        setValue(row, col++, item.getEmpdivision());
    }

    @Override
    public void fillSearchCriteria(int row) {
        useCriteriaSheet();

        setLeftHeader(row, 0, "employee_id");
        setValue(row++, 1, sf.getEmployee().getId());
        setSelector(row++, 0, "employee_empuhnumber", sf.getEmpuhnumberSelector());
        setSelector(row++, 0, "employee_empfirstname", sf.getEmpfirstnameSelector());
        setSelector(row++, 0, "employee_emplastname", sf.getEmplastnameSelector());
        setSelector(row++, 0, "employee_emprole", sf.getEmproleSelector());
        setSelector(row++, 0, "employee_empdivision", sf.getEmpdivisionSelector());
        setSelector(row++, 0, "employee_empstatus", sf.getEmpstatusSelector());
    }
}