/*
 * Source code generated by Celerio, a Jaxio product.
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Follow us on twitter: @jaxiosoft
 * Need commercial support ? Contact us: info@jaxio.com
 * Template pack-jsf2-spring-conversation:src/main/java/domain/ExcelExporter.e.vm.java
 * Template is part of Open Source Project: https://github.com/jaxio/pack-jsf2-spring-conversation
 */
package com.jaxio.jsf2_spring_conversation_empty.web.domain;

import javax.inject.Inject;
import javax.inject.Named;

import com.jaxio.jsf2_spring_conversation_empty.domain.Empmanager;
import com.jaxio.jsf2_spring_conversation_empty.web.domain.support.GenericExcelExporter;
import com.jaxio.jsf2_spring_conversation_empty.web.faces.ConversationContextScoped;

/**
 * Exports to excel document {@link Empmanager} search criteria and result. 
 */
@Named
@ConversationContextScoped
public class EmpmanagerExcelExporter extends GenericExcelExporter<Empmanager> {
    @Inject
    protected EmpmanagerSearchForm sf;

    public EmpmanagerExcelExporter() {
        super("empmanager_division");
    }

    @Override
    protected void fillResultItem(int row, Empmanager item) {
        int col = 0;
        setValue(row, col++, item.getDivision());
    }

    @Override
    public void fillSearchCriteria(int row) {
        useCriteriaSheet();

        setSelectedEntities(row++, 0, "empmanager_employee", sf.getEmployeeSelector().getSelected());
        setSelector(row++, 0, "empmanager_division", sf.getDivisionSelector());
    }
}