/*
 * Source code generated by Celerio, a Jaxio product.
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Follow us on twitter: @jaxiosoft
 * Need commercial support ? Contact us: info@jaxio.com
 * Template pack-jsf2-spring-conversation:src/main/java/domain/Controller.e.vm.java
 * Template is part of Open Source Project: https://github.com/jaxio/pack-jsf2-spring-conversation
 */
package com.jaxio.jsf2_spring_conversation_empty.web.domain;

import javax.inject.Inject;
import javax.inject.Named;
import javax.inject.Singleton;

import com.jaxio.jsf2_spring_conversation_empty.domain.Empmanager;
import com.jaxio.jsf2_spring_conversation_empty.printer.EmpmanagerPrinter;
import com.jaxio.jsf2_spring_conversation_empty.repository.EmpmanagerRepository;
import com.jaxio.jsf2_spring_conversation_empty.web.domain.support.GenericController;
import com.jaxio.jsf2_spring_conversation_empty.web.permission.EmpmanagerPermission;

/**
 * Stateless controller for {@link Empmanager} conversation start.
 */
@Named
@Singleton
public class EmpmanagerController extends GenericController<Empmanager, Integer> {
    public static final String EMPMANAGER_EDIT_URI = "/domain/empmanagerEdit.faces";
    public static final String EMPMANAGER_SELECT_URI = "/domain/empmanagerSelect.faces";

    @Inject
    public EmpmanagerController(EmpmanagerRepository empmanagerRepository, EmpmanagerPermission empmanagerPermission, EmpmanagerPrinter empmanagerPrinter) {
        super(empmanagerRepository, empmanagerPermission, empmanagerPrinter, EMPMANAGER_SELECT_URI, EMPMANAGER_EDIT_URI);
    }
}