/*
 * Source code generated by Celerio, a Jaxio product.
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Follow us on twitter: @jaxiosoft
 * Need commercial support ? Contact us: info@jaxio.com
 * Template pack-jsf2-spring-conversation:src/main/java/domain/ExcelExporter.e.vm.java
 * Template is part of Open Source Project: https://github.com/jaxio/pack-jsf2-spring-conversation
 */
package com.jaxio.jsf2_spring_conversation_bank.web.domain;

import javax.inject.Inject;
import javax.inject.Named;

import com.jaxio.jsf2_spring_conversation_bank.domain.Account;
import com.jaxio.jsf2_spring_conversation_bank.web.domain.support.GenericExcelExporter;
import com.jaxio.jsf2_spring_conversation_bank.web.faces.ConversationContextScoped;

/**
 * Exports to excel document {@link Account} search criteria and result. 
 */
@Named
@ConversationContextScoped
public class AccountExcelExporter extends GenericExcelExporter<Account> {
    @Inject
    protected AccountSearchForm sf;

    public AccountExcelExporter() {
        super("account_accountNumber", "account_name", "account_customer");
    }

    @Override
    protected void fillResultItem(int row, Account item) {
        int col = 0;
        setValue(row, col++, item.getAccountNumber());
        setValue(row, col++, item.getName());
        setEntity(row, col++, item.getCustomer());
    }

    @Override
    public void fillSearchCriteria(int row) {
        useCriteriaSheet();

        setSelector(row++, 0, "account_accountNumber", sf.getAccountNumberSelector());
        setSelector(row++, 0, "account_name", sf.getNameSelector());
        setSelectedEntities(row++, 0, "account_currency", sf.getCurrencySelector().getSelected());
        setSelectedEntities(row++, 0, "account_customer", sf.getCustomerSelector().getSelected());
    }
}