/*
 * Source code generated by Celerio, a Jaxio product.
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Follow us on twitter: @jaxiosoft
 * Need commercial support ? Contact us: info@jaxio.com
 * Template pack-jsf2-spring-conversation:src/main/java/domain/Controller.e.vm.java
 * Template is part of Open Source Project: https://github.com/jaxio/pack-jsf2-spring-conversation
 */
package com.jaxio.jsf2_spring_conversation_bank.web.domain;

import javax.inject.Inject;
import javax.inject.Named;
import javax.inject.Singleton;

import com.jaxio.jpa.querybyexample.SearchParameters;
import com.jaxio.jsf2_spring_conversation_bank.domain.Account;
import com.jaxio.jsf2_spring_conversation_bank.domain.Account_;
import com.jaxio.jsf2_spring_conversation_bank.printer.AccountPrinter;
import com.jaxio.jsf2_spring_conversation_bank.repository.AccountRepository;
import com.jaxio.jsf2_spring_conversation_bank.web.domain.support.GenericController;
import com.jaxio.jsf2_spring_conversation_bank.web.permission.AccountPermission;

/**
 * Stateless controller for {@link Account} conversation start.
 */
@Named
@Singleton
public class AccountController extends GenericController<Account, Integer> {
    public static final String ACCOUNT_EDIT_URI = "/domain/accountEdit.faces";
    public static final String ACCOUNT_SELECT_URI = "/domain/accountSelect.faces";

    @Inject
    public AccountController(AccountRepository accountRepository, AccountPermission accountPermission, AccountPrinter accountPrinter) {
        super(accountRepository, accountPermission, accountPrinter, ACCOUNT_SELECT_URI, ACCOUNT_EDIT_URI);
    }

    @Override
    protected SearchParameters defaultOrder(SearchParameters searchParameters) {
        return searchParameters.asc(Account_.accountNumber);
    }
}