/*
 * Source code generated by Celerio, a Jaxio product.
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Follow us on twitter: @jaxiosoft
 * Need commercial support ? Contact us: info@jaxio.com
 * Template pack-jsf2-spring-conversation:src/main/java/domain/SearchForm.e.vm.java
 * Template is part of Open Source Project: https://github.com/jaxio/pack-jsf2-spring-conversation
 */
package com.jaxio.jsf2_spring_conversation_bank.web.domain;

import static com.jaxio.jpa.querybyexample.PropertySelector.newPropertySelector;
import static com.jaxio.jpa.querybyexample.Range.newRange;

import javax.inject.Named;

import com.jaxio.jpa.querybyexample.PropertySelector;
import com.jaxio.jpa.querybyexample.Range;
import com.jaxio.jpa.querybyexample.SearchParameters;
import com.jaxio.jsf2_spring_conversation_bank.domain.Currency;
import com.jaxio.jsf2_spring_conversation_bank.domain.Currency_;
import com.jaxio.jsf2_spring_conversation_bank.web.domain.support.GenericSearchForm;
import com.jaxio.jsf2_spring_conversation_bank.web.faces.ConversationContextScoped;

/**
 * View Helper to search {@link Currency}.
 * It exposes a {@link Currency} instance so it can be used in search by-example-query.
 */
@Named
@ConversationContextScoped
public class CurrencySearchForm extends GenericSearchForm<Currency, Integer, CurrencySearchForm> {
    private static final long serialVersionUID = 1L;
    protected Currency currency = new Currency();
    protected Range<Currency, Integer> decimalCountRange = newRange(Currency_.decimalCount);
    protected PropertySelector<Currency, String> codeSelector = newPropertySelector(Currency_.code);
    protected PropertySelector<Currency, String> nameSelector = newPropertySelector(Currency_.name);
    protected PropertySelector<Currency, Integer> decimalCountSelector = newPropertySelector(Currency_.decimalCount);

    public Currency getCurrency() {
        return currency;
    }

    @Override
    protected Currency getEntity() {
        return getCurrency();
    }

    @Override
    public CurrencySearchForm newInstance() {
        return new CurrencySearchForm();
    }

    @Override
    public SearchParameters toSearchParameters() {
        SearchParameters sp = searchParameters();
        sp.range(decimalCountRange);
        sp.property(codeSelector, nameSelector, decimalCountSelector);
        return sp;
    }

    @Override
    public void resetWithOther(CurrencySearchForm other) {
        this.currency = other.getCurrency();
        this.decimalCountRange = other.getDecimalCountRange();
        this.codeSelector = other.getCodeSelector();
        this.nameSelector = other.getNameSelector();
        this.decimalCountSelector = other.getDecimalCountSelector();
    }

    // Ranges
    public Range<Currency, Integer> getDecimalCountRange() {
        return decimalCountRange;
    }

    // Property selectors
    public PropertySelector<Currency, String> getCodeSelector() {
        return codeSelector;
    }

    public PropertySelector<Currency, String> getNameSelector() {
        return nameSelector;
    }

    public PropertySelector<Currency, Integer> getDecimalCountSelector() {
        return decimalCountSelector;
    }
}
