/*
 * Source code generated by Celerio, a Jaxio product.
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Follow us on twitter: @jaxiosoft
 * Need commercial support ? Contact us: info@jaxio.com
 * Template pack-jsf2-spring-conversation:src/main/java/domain/EditForm.e.vm.java
 * Template is part of Open Source Project: https://github.com/jaxio/pack-jsf2-spring-conversation
 */
package com.jaxio.jsf2_spring_conversation_bank.web.domain;

import javax.inject.Inject;
import javax.inject.Named;

import com.jaxio.jsf2_spring_conversation_bank.domain.Currency;
import com.jaxio.jsf2_spring_conversation_bank.repository.CurrencyRepository;
import com.jaxio.jsf2_spring_conversation_bank.web.domain.support.GenericEditForm;
import com.jaxio.jsf2_spring_conversation_bank.web.faces.ConversationContextScoped;

/**
 * View Helper/Controller to edit {@link Currency}.
 */
@Named
@ConversationContextScoped
public class CurrencyEditForm extends GenericEditForm<Currency, Integer> {
    @Inject
    protected CurrencyController currencyController;

    @Inject
    public CurrencyEditForm(CurrencyRepository currencyRepository) {
        super(currencyRepository);
    }

    /**
     * The entity to edit/view.
     */
    public Currency getCurrency() {
        return getEntity();
    }

    public String print() {
        return currencyController.print(getCurrency());
    }
}
