/*
 * Source code generated by Celerio, a Jaxio product.
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Follow us on twitter: @jaxiosoft
 * Need commercial support ? Contact us: info@jaxio.com
 * Template pack-jsf2-spring-conversation:src/main/java/domain/Controller.e.vm.java
 * Template is part of Open Source Project: https://github.com/jaxio/pack-jsf2-spring-conversation
 */
package com.jaxio.jsf2_spring_conversation_bank.web.domain;

import javax.inject.Inject;
import javax.inject.Named;
import javax.inject.Singleton;

import com.jaxio.jsf2_spring_conversation_bank.domain.Currency;
import com.jaxio.jsf2_spring_conversation_bank.printer.CurrencyPrinter;
import com.jaxio.jsf2_spring_conversation_bank.repository.CurrencyRepository;
import com.jaxio.jsf2_spring_conversation_bank.web.domain.support.GenericController;
import com.jaxio.jsf2_spring_conversation_bank.web.permission.CurrencyPermission;

/**
 * Stateless controller for {@link Currency} conversation start.
 */
@Named
@Singleton
public class CurrencyController extends GenericController<Currency, Integer> {
    public static final String CURRENCY_EDIT_URI = "/domain/currencyEdit.faces";
    public static final String CURRENCY_SELECT_URI = "/domain/currencySelect.faces";

    @Inject
    public CurrencyController(CurrencyRepository currencyRepository, CurrencyPermission currencyPermission, CurrencyPrinter currencyPrinter) {
        super(currencyRepository, currencyPermission, currencyPrinter, CURRENCY_SELECT_URI, CURRENCY_EDIT_URI);
    }
}