/*
 * Source code generated by Celerio, a Jaxio product.
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Follow us on twitter: @jaxiosoft
 * Need commercial support ? Contact us: info@jaxio.com
 * Template pack-jsf2-spring-conversation:src/main/java/domain/Controller.e.vm.java
 * Template is part of Open Source Project: https://github.com/jaxio/pack-jsf2-spring-conversation
 */
package com.jaxio.jsf2_spring_conversation_bank.web.domain;

import javax.inject.Inject;
import javax.inject.Named;
import javax.inject.Singleton;

import com.jaxio.jsf2_spring_conversation_bank.domain.Customer;
import com.jaxio.jsf2_spring_conversation_bank.printer.CustomerPrinter;
import com.jaxio.jsf2_spring_conversation_bank.repository.CustomerRepository;
import com.jaxio.jsf2_spring_conversation_bank.web.domain.support.GenericController;
import com.jaxio.jsf2_spring_conversation_bank.web.permission.CustomerPermission;

/**
 * Stateless controller for {@link Customer} conversation start.
 */
@Named
@Singleton
public class CustomerController extends GenericController<Customer, Integer> {
    public static final String CUSTOMER_EDIT_URI = "/domain/customerEdit.faces";
    public static final String CUSTOMER_SELECT_URI = "/domain/customerSelect.faces";

    @Inject
    public CustomerController(CustomerRepository customerRepository, CustomerPermission customerPermission, CustomerPrinter customerPrinter) {
        super(customerRepository, customerPermission, customerPrinter, CUSTOMER_SELECT_URI, CUSTOMER_EDIT_URI);
    }

    public CustomerFileUpload getCustomerFileUpload(Customer customer) {
        return new CustomerFileUpload(customer);
    }
}