/*
 * Source code generated by Celerio, a Jaxio product.
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Follow us on twitter: @jaxiosoft
 * Need commercial support ? Contact us: info@jaxio.com
 * Template pack-jsf2-spring-conversation:src/main/java/domain/FileDownload.e.vm.java
 * Template is part of Open Source Project: https://github.com/jaxio/pack-jsf2-spring-conversation
 */
package com.jaxio.jsf2_spring_conversation_bank.web.domain;

import javax.inject.Inject;
import javax.inject.Named;
import javax.inject.Singleton;

import org.primefaces.model.StreamedContent;

import com.jaxio.jsf2_spring_conversation_bank.domain.Customer;
import com.jaxio.jsf2_spring_conversation_bank.domain.Customer_;
import com.jaxio.jsf2_spring_conversation_bank.repository.CustomerRepository;
import com.jaxio.jsf2_spring_conversation_bank.web.domain.support.ByteArrayStreamedContent;

/**
 * Stateless controller to download {@link Customer} binaries 
 */
@Named
@Singleton
public class CustomerFileDownload {
    @Inject
    private CustomerRepository customerRepository;

    /**
     * Primefaces support for contractBinary file download.
     */
    public StreamedContent getContractBinaryStream(final Customer customer) {
        // check whether the binary is null WITHOUT downloading it.
        if (customer.isIdSet()) {
            if (customerRepository.isPropertyNull(customer.getId(), Customer_.contractBinary)) {
                return null;
            }
        } else if (customer.getContractBinary() == null) {
            return null;
        }

        ByteArrayStreamedContent basc = new ByteArrayStreamedContent() {
            @Override
            public byte[] getByteArray() {
                return customerRepository.getContractBinary(customer);
            }
        };
        basc.setContentType(customer.getContractContentType());
        basc.setName(customer.getContractFileName());
        return basc;
    }
}