/*
 * Source code generated by Celerio, a Jaxio product.
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Follow us on twitter: @jaxiosoft
 * Need commercial support ? Contact us: info@jaxio.com
 * Template pack-jsf2-spring-conversation:src/main/java/domain/LazyDataModel.e.vm.java
 * Template is part of Open Source Project: https://github.com/jaxio/pack-jsf2-spring-conversation
 */
package com.jaxio.jsf2_spring_conversation_bank.web.domain;

import javax.inject.Inject;
import javax.inject.Named;

import org.primefaces.model.LazyDataModel;

import com.jaxio.jsf2_spring_conversation_bank.domain.Customer;
import com.jaxio.jsf2_spring_conversation_bank.repository.CustomerRepository;
import com.jaxio.jsf2_spring_conversation_bank.web.domain.support.GenericLazyDataModel;
import com.jaxio.jsf2_spring_conversation_bank.web.faces.ConversationContextScoped;

/**
 * Provide PrimeFaces {@link LazyDataModel} for {@link Customer}
 */
@Named
@ConversationContextScoped
public class CustomerLazyDataModel extends GenericLazyDataModel<Customer, Integer, CustomerSearchForm> {
    private static final long serialVersionUID = 1L;

    @Inject
    public CustomerLazyDataModel(CustomerRepository customerRepository, CustomerController customerController, CustomerSearchForm customerSearchForm,
            CustomerExcelExporter customerExcelExporter) {
        super(customerRepository, customerController, customerSearchForm, customerExcelExporter);
    }
}