/*
 * Source code generated by Celerio, a Jaxio product.
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Follow us on twitter: @jaxiosoft
 * Need commercial support ? Contact us: info@jaxio.com
 * Template pack-jsf2-spring-conversation:src/main/java/domain/ExcelExporter.e.vm.java
 * Template is part of Open Source Project: https://github.com/jaxio/pack-jsf2-spring-conversation
 */
package com.jaxio.jsf2_spring_conversation_bank.web.domain;

import javax.inject.Inject;
import javax.inject.Named;

import com.jaxio.jsf2_spring_conversation_bank.domain.Role;
import com.jaxio.jsf2_spring_conversation_bank.web.domain.support.GenericExcelExporter;
import com.jaxio.jsf2_spring_conversation_bank.web.faces.ConversationContextScoped;

/**
 * Exports to excel document {@link Role} search criteria and result. 
 */
@Named
@ConversationContextScoped
public class RoleExcelExporter extends GenericExcelExporter<Role> {
    @Inject
    protected RoleSearchForm sf;

    public RoleExcelExporter() {
        super("role_roleName");
    }

    @Override
    protected void fillResultItem(int row, Role item) {
        int col = 0;
        setValue(row, col++, item.getRoleName());
    }

    @Override
    public void fillSearchCriteria(int row) {
        useCriteriaSheet();
        setTermSelector(row++, 0, "role_roleName", sf.getRoleNameTermSelector());

        setSelector(row++, 0, "role_roleName", sf.getRoleNameSelector());
    }
}