/*
 * Source code generated by Celerio, a Jaxio product.
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Follow us on twitter: @jaxiosoft
 * Need commercial support ? Contact us: info@jaxio.com
 * Template pack-jsf2-spring-conversation:src/main/java/domain/Controller.e.vm.java
 * Template is part of Open Source Project: https://github.com/jaxio/pack-jsf2-spring-conversation
 */
package com.jaxio.jsf2_spring_conversation_bank.web.domain;

import javax.inject.Inject;
import javax.inject.Named;
import javax.inject.Singleton;

import com.jaxio.jpa.querybyexample.SearchParameters;
import com.jaxio.jsf2_spring_conversation_bank.domain.Role;
import com.jaxio.jsf2_spring_conversation_bank.domain.Role_;
import com.jaxio.jsf2_spring_conversation_bank.printer.RolePrinter;
import com.jaxio.jsf2_spring_conversation_bank.repository.RoleRepository;
import com.jaxio.jsf2_spring_conversation_bank.web.domain.support.GenericController;
import com.jaxio.jsf2_spring_conversation_bank.web.permission.RolePermission;

/**
 * Stateless controller for {@link Role} conversation start.
 */
@Named
@Singleton
public class RoleController extends GenericController<Role, Integer> {
    public static final String ROLE_EDIT_URI = "/domain/roleEdit.faces";
    public static final String ROLE_SELECT_URI = "/domain/roleSelect.faces";

    @Inject
    public RoleController(RoleRepository roleRepository, RolePermission rolePermission, RolePrinter rolePrinter) {
        super(roleRepository, rolePermission, rolePrinter, ROLE_SELECT_URI, ROLE_EDIT_URI);
    }

    @Override
    protected SearchParameters defaultOrder(SearchParameters searchParameters) {
        return searchParameters.asc(Role_.roleName);
    }
}