/*
 * Source code generated by Celerio, a Jaxio product.
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Follow us on twitter: @jaxiosoft
 * Need commercial support ? Contact us: info@jaxio.com
 * Template pack-jsf2-spring-conversation:src/main/java/domain/EditForm.e.vm.java
 * Template is part of Open Source Project: https://github.com/jaxio/pack-jsf2-spring-conversation
 */
package com.jaxio.jsf2_spring_conversation_bank.web.domain;

import javax.annotation.PostConstruct;
import javax.inject.Inject;
import javax.inject.Named;

import com.jaxio.jsf2_spring_conversation_bank.domain.SavedSearch;
import com.jaxio.jsf2_spring_conversation_bank.domain.SavedSearch_;
import com.jaxio.jsf2_spring_conversation_bank.domain.User;
import com.jaxio.jsf2_spring_conversation_bank.repository.SavedSearchRepository;
import com.jaxio.jsf2_spring_conversation_bank.web.domain.support.GenericEditForm;
import com.jaxio.jsf2_spring_conversation_bank.web.domain.support.GenericToOneAssociation;
import com.jaxio.jsf2_spring_conversation_bank.web.faces.ConversationContextScoped;

/**
 * View Helper/Controller to edit {@link SavedSearch}.
 */
@Named
@ConversationContextScoped
public class SavedSearchEditForm extends GenericEditForm<SavedSearch, Integer> {
    @Inject
    protected SavedSearchController savedSearchController;
    @Inject
    protected UserController userController;
    protected GenericToOneAssociation<User, Integer> user;

    @Inject
    public SavedSearchEditForm(SavedSearchRepository savedSearchRepository, SavedSearchGraphLoader savedSearchGraphLoader) {
        super(savedSearchRepository, savedSearchGraphLoader);
    }

    /**
     * The entity to edit/view.
     */
    public SavedSearch getSavedSearch() {
        return getEntity();
    }

    public String print() {
        return savedSearchController.print(getSavedSearch());
    }

    @PostConstruct
    void setupUserActions() {
        user = new GenericToOneAssociation<User, Integer>(userController, SavedSearch_.user) {
            @Override
            protected User get() {
                return getSavedSearch().getUser();
            }

            @Override
            protected void set(User user) {
                getSavedSearch().setUser(user);
            }
        };
    }

    public GenericToOneAssociation<User, Integer> getUser() {
        return user;
    }
}
