/*
 * Source code generated by Celerio, a Jaxio product.
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Follow us on twitter: @jaxiosoft
 * Need commercial support ? Contact us: info@jaxio.com
 * Template pack-jsf2-spring-conversation:src/main/java/domain/LazyDataModel.e.vm.java
 * Template is part of Open Source Project: https://github.com/jaxio/pack-jsf2-spring-conversation
 */
package com.jaxio.jsf2_spring_conversation_bank.web.domain;

import javax.inject.Inject;
import javax.inject.Named;

import org.primefaces.model.LazyDataModel;

import com.jaxio.jsf2_spring_conversation_bank.domain.Transaction;
import com.jaxio.jsf2_spring_conversation_bank.repository.TransactionRepository;
import com.jaxio.jsf2_spring_conversation_bank.web.domain.support.GenericLazyDataModel;
import com.jaxio.jsf2_spring_conversation_bank.web.faces.ConversationContextScoped;

/**
 * Provide PrimeFaces {@link LazyDataModel} for {@link Transaction}
 */
@Named
@ConversationContextScoped
public class TransactionLazyDataModel extends GenericLazyDataModel<Transaction, Integer, TransactionSearchForm> {
    private static final long serialVersionUID = 1L;

    @Inject
    public TransactionLazyDataModel(TransactionRepository transactionRepository, TransactionController transactionController,
            TransactionSearchForm transactionSearchForm, TransactionExcelExporter transactionExcelExporter) {
        super(transactionRepository, transactionController, transactionSearchForm, transactionExcelExporter);
    }
}