/*
 * Source code generated by Celerio, a Jaxio product.
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Follow us on twitter: @jaxiosoft
 * Need commercial support ? Contact us: info@jaxio.com
 * Template pack-jsf2-spring-conversation:src/main/java/domain/Controller.e.vm.java
 * Template is part of Open Source Project: https://github.com/jaxio/pack-jsf2-spring-conversation
 */
package com.jaxio.jsf2_spring_conversation_bank.web.domain;

import javax.inject.Inject;
import javax.inject.Named;
import javax.inject.Singleton;

import com.jaxio.jsf2_spring_conversation_bank.domain.Transaction;
import com.jaxio.jsf2_spring_conversation_bank.printer.TransactionPrinter;
import com.jaxio.jsf2_spring_conversation_bank.repository.TransactionRepository;
import com.jaxio.jsf2_spring_conversation_bank.web.domain.support.GenericController;
import com.jaxio.jsf2_spring_conversation_bank.web.permission.TransactionPermission;

/**
 * Stateless controller for {@link Transaction} conversation start.
 */
@Named
@Singleton
public class TransactionController extends GenericController<Transaction, Integer> {
    public static final String TRANSACTION_EDIT_URI = "/domain/transactionEdit.faces";
    public static final String TRANSACTION_SELECT_URI = "/domain/transactionSelect.faces";

    @Inject
    public TransactionController(TransactionRepository transactionRepository, TransactionPermission transactionPermission, TransactionPrinter transactionPrinter) {
        super(transactionRepository, transactionPermission, transactionPrinter, TRANSACTION_SELECT_URI, TRANSACTION_EDIT_URI);
    }
}