/*
 * Source code generated by Celerio, a Jaxio product.
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Follow us on twitter: @jaxiosoft
 * Need commercial support ? Contact us: info@jaxio.com
 * Template pack-jsf2-spring-conversation:src/main/java/domain/GraphLoader.e.vm.java
 * Template is part of Open Source Project: https://github.com/jaxio/pack-jsf2-spring-conversation
 */
package com.jaxio.jsf2_spring_conversation_bank.web.domain;

import javax.inject.Inject;
import javax.inject.Named;
import javax.inject.Singleton;

import com.jaxio.jpa.querybyexample.EntityGraphLoader;
import com.jaxio.jsf2_spring_conversation_bank.domain.User;
import com.jaxio.jsf2_spring_conversation_bank.repository.UserRepository;

/**
 * Preloads the {@link User} associations required by the view layer.
 * 
 * Do not use other GraphLoaders in this GraphLoader. 
 */
@Named
@Singleton
public class UserGraphLoader extends EntityGraphLoader<User, Integer> {
    // required by cglib to create a proxy around the object as we are using the @Transactional annotation
    protected UserGraphLoader() {
        super();
    }

    @Inject
    public UserGraphLoader(UserRepository userRepository) {
        super(userRepository);
    }

    @Override
    public void loadGraph(User user) {
        loadCollection(user.getSecurityRoles());
    }
}