/*
 * Source code generated by Celerio, a Jaxio product.
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Follow us on twitter: @jaxiosoft
 * Need commercial support ? Contact us: info@jaxio.com
 * Template pack-jsf2-spring-conversation:src/main/java/domain/EditForm.e.vm.java
 * Template is part of Open Source Project: https://github.com/jaxio/pack-jsf2-spring-conversation
 */
package com.jaxio.jsf2_spring_conversation_bank.web.domain;

import javax.annotation.PostConstruct;
import javax.inject.Inject;
import javax.inject.Named;

import com.jaxio.jsf2_spring_conversation_bank.domain.Role;
import com.jaxio.jsf2_spring_conversation_bank.domain.User;
import com.jaxio.jsf2_spring_conversation_bank.domain.User_;
import com.jaxio.jsf2_spring_conversation_bank.repository.UserRepository;
import com.jaxio.jsf2_spring_conversation_bank.web.domain.support.GenericEditForm;
import com.jaxio.jsf2_spring_conversation_bank.web.domain.support.GenericToManyAssociation;
import com.jaxio.jsf2_spring_conversation_bank.web.faces.ConversationContextScoped;
import com.jaxio.jsf2_spring_conversation_bank.web.util.TabBean;

/**
 * View Helper/Controller to edit {@link User}.
 */
@Named
@ConversationContextScoped
public class UserEditForm extends GenericEditForm<User, Integer> {
    @Inject
    protected UserController userController;
    @Inject
    protected RoleController roleController;
    protected GenericToManyAssociation<Role, Integer> securityRoles;
    protected TabBean tabBean = new TabBean();

    @Inject
    public UserEditForm(UserRepository userRepository, UserGraphLoader userGraphLoader) {
        super(userRepository, userGraphLoader);
    }

    /**
     * View helper to store the x-to-many associations tab's index. 
     */
    @Override
    public TabBean getTabBean() {
        return tabBean;
    }

    /**
     * The entity to edit/view.
     */
    public User getUser() {
        return getEntity();
    }

    public String print() {
        return userController.print(getUser());
    }

    @PostConstruct
    void setupSecurityRolesActions() {
        securityRoles = new GenericToManyAssociation<Role, Integer>(getUser().getSecurityRoles(), roleController, User_.securityRoles) {
            @Override
            protected void remove(Role role) {
                getUser().removeSecurityRole(role);
            }

            @Override
            protected void add(Role role) {
                // add the object only to the securityRole side of the relation 
                getUser().getSecurityRoles().add(role);
            }
        };
    }

    public GenericToManyAssociation<Role, Integer> getSecurityRoles() {
        return securityRoles;
    }
}
