/*
 * Source code generated by Celerio, a Jaxio product.
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Follow us on twitter: @jaxiosoft
 * Need commercial support ? Contact us: info@jaxio.com
 * Template pack-javaee7-frontend:src/main/java/domain/support/CommonAction.p.vm.java
 * Template is part of Open Source Project: https://github.com/jaxio/javaee-lab
 */
package com.jaxio.javaee7_wildfly_bank.web.domain.support;

import java.io.Serializable;

/**
 * Simple actions that can be shared.
 */
public abstract class CommonAction<E> implements Serializable {

    /**
     * Quit the page and go back home.
     */
    public String quit() {
        return "/home.faces?faces-redirect=true";
    }
}