/*
 * Source code generated by Celerio, a Jaxio product.
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Follow us on twitter: @jaxiosoft
 * Need commercial support ? Contact us: info@jaxio.com
 * Template pack-backend-jpa:src/main/java/domain/EntityMeta_.e.vm.java
 * Template is part of Open Source Project: https://github.com/jaxio/pack-backend-jpa
 */
package com.jaxio.jsf2_spring_conversation_empty.domain;

import java.util.Date;

import javax.persistence.metamodel.SingularAttribute;
import javax.persistence.metamodel.StaticMetamodel;

@StaticMetamodel(Absentlog.class)
public abstract class Absentlog_ {

    // Raw attributes
    public static volatile SingularAttribute<Absentlog, Integer> id;
    public static volatile SingularAttribute<Absentlog, Date> logdate;
    public static volatile SingularAttribute<Absentlog, Integer> logversionid;
    public static volatile SingularAttribute<Absentlog, String> lognotes;

    // Many to one
    public static volatile SingularAttribute<Absentlog, Employee> employee;
    public static volatile SingularAttribute<Absentlog, Absent> abs;
}