/*
 * Source code generated by Celerio, a Jaxio product.
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Follow us on twitter: @jaxiosoft
 * Need commercial support ? Contact us: info@jaxio.com
 * Template pack-backend-jpa:src/main/java/domain/EntityMeta_.e.vm.java
 * Template is part of Open Source Project: https://github.com/jaxio/pack-backend-jpa
 */
package com.jaxio.jsf2_spring_conversation_empty.domain;

import javax.persistence.metamodel.SingularAttribute;
import javax.persistence.metamodel.StaticMetamodel;

@StaticMetamodel(Employee.class)
public abstract class Employee_ {

    // Raw attributes
    public static volatile SingularAttribute<Employee, Integer> id;
    public static volatile SingularAttribute<Employee, String> empuhnumber;
    public static volatile SingularAttribute<Employee, String> empfirstname;
    public static volatile SingularAttribute<Employee, String> emplastname;
    public static volatile SingularAttribute<Employee, String> emprole;
    public static volatile SingularAttribute<Employee, String> empdivision;
    public static volatile SingularAttribute<Employee, String> empstatus;
}