/*
 * Source code generated by Celerio, a Jaxio product.
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Follow us on twitter: @jaxiosoft
 * Need commercial support ? Contact us: info@jaxio.com
 * Template pack-javaee7-frontend:src/main/java/util/MessageBundle.p.vm.java
 * Template is part of Open Source Project: https://github.com/jaxio/javaee-lab
 */
package com.jaxio.javaee7_wildfly_bank.web.util;

import java.util.Enumeration;
import java.util.ResourceBundle;

import com.jaxio.javaee7_wildfly_bank.util.ResourcesUtil;

/**
 * This {@link ResourceBundle} is set in faces-config.xml under <code>msg</code> var.
 * <p>
 * From your JSF2 pages, you may use <code>#{msg.property_key}</code>.
 * <p>
 * _HACK_ as it is a tricky integration point.
 */
public class MessageBundle extends ResourceBundle {

    private ResourcesUtil resourcesUtil;

    @Override
    public Enumeration<String> getKeys() {
        return null;
    }

    @Override
    protected Object handleGetObject(String key) {
        if (resourcesUtil == null) {
            resourcesUtil = ResourcesUtil.getInstance();
        }

        if (resourcesUtil == null) {
            System.out.println("===> TODO key=" + key + " requested on startup, why ? => returns null");
            return null;
        }

        return resourcesUtil.getProperty(key);
    }
}