/*
 * Source code generated by Celerio, a Jaxio product.
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Follow us on twitter: @jaxiosoft
 * Need commercial support ? Contact us: info@jaxio.com
 * Template pack-javaee7-frontend:src/main/java/util/Message.p.vm.java
 * Template is part of Open Source Project: https://github.com/jaxio/javaee-lab
 */
package com.jaxio.javaee7_wildfly_bank.web.util;

import javax.faces.application.FacesMessage;

/**
 * Integration _HACK_ : would be nice if jsf was providing the id...
 * Wrap {@link FacesMessage} along with the id of the associated component.
 */
public class Message {

    private String sourceId;
    private FacesMessage facesMessage;

    public Message(String sourceId, FacesMessage facesMessage) {
        this.sourceId = sourceId;
        this.facesMessage = facesMessage;
    }

    public String getSourceId() {
        return sourceId;
    }

    public FacesMessage getFacesMessage() {
        return facesMessage;
    }

    public String getSeverity() {
        return MessageUtil.toCssFriendly(facesMessage.getSeverity());
    }
}
