/*
 * Source code generated by Celerio, a Jaxio product.
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Follow us on twitter: @jaxiosoft
 * Need commercial support ? Contact us: info@jaxio.com
 * Template pack-javaee7-backend:src/main/java/util/MessageSource.p.vm.java
 * Template is part of Open Source Project: https://github.com/jaxio/javaee-lab
 */
package com.jaxio.javaee7_wildfly_bank.util;

import java.util.Locale;

public interface MessageSource {
    void setBasenames(String... basenames);

    String getMessage(String key, Locale locale);

    String getMessage(String key, Object[] args, Locale locale);
}