/*
 * Source code generated by Celerio, a Jaxio product.
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Follow us on twitter: @jaxiosoft
 * Need commercial support ? Contact us: info@jaxio.com
 * Template pack-backend-jpa:src/main/java/repository/Repository.e.vm.java
 * Template is part of Open Source Project: https://github.com/jaxio/pack-backend-jpa
 */
package com.jaxio.backend_jpa_bank.repository;

import javax.inject.Named;
import javax.inject.Singleton;

import org.hibernate.LazyInitializationException;
import org.springframework.transaction.annotation.Transactional;

import com.jaxio.backend_jpa_bank.domain.Customer;
import com.jaxio.jpa.querybyexample.GenericRepository;

/**
 * {@link GenericRepository} for {@link Customer} 
 */
@Named
@Singleton
public class CustomerRepository extends GenericRepository<Customer, Integer> {

    public CustomerRepository() {
        super(Customer.class);
    }

    @Override
    public Customer getNew() {
        return new Customer();
    }

    @Override
    public Customer getNewWithDefaults() {
        return getNew().withDefaults();
    }

    /**
     * Safe way to load the contractBinary content. 
     */
    @Transactional(readOnly = true)
    public byte[] getContractBinary(Customer customer) {
        if (!customer.isIdSet()) {
            return customer.getContractBinary();
        }

        try {
            return customer.getContractBinary();
        } catch (LazyInitializationException lie) { // _HACK_ as we still rely on hibernate here
            return get(customer).getContractBinary();
        }
    }
}