/*
 * Source code generated by Celerio, a Jaxio product.
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Follow us on twitter: @jaxiosoft
 * Need commercial support ? Contact us: info@jaxio.com
 * Template pack-backend-jpa:src/main/java/enum/Enum.enum.vm.java
 * Template is part of Open Source Project: https://github.com/jaxio/pack-backend-jpa
 */
package com.jaxio.jsf2_spring_conversation_bank.domain;

import com.jaxio.jpa.querybyexample.LabelizedEnum;
import com.jaxio.jsf2_spring_conversation_bank.util.ResourcesUtil;

public enum Civility implements LabelizedEnum {
    MR, //
    MS;

    @Override
    public String getLabel() {
        return ResourcesUtil.getInstance().getProperty("Civility_" + name());
    }

    public static Civility fromLabel(String label) {
        if (label == null) {
            return null;
        }
        for (Civility enumValue : Civility.values()) {
            if (label.equals(enumValue.getLabel())) {
                return enumValue;
            }
        }
        return null;
    }
}