/*
 * Source code generated by Celerio, a Jaxio product.
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Follow us on twitter: @jaxiosoft
 * Need commercial support ? Contact us: info@jaxio.com
 * Template pack-backend-jpa:src/main/java/domain/EntityMeta_.e.vm.java
 * Template is part of Open Source Project: https://github.com/jaxio/pack-backend-jpa
 */
package com.jaxio.jsf2_spring_conversation_bank.domain;

import javax.persistence.metamodel.ListAttribute;
import javax.persistence.metamodel.SingularAttribute;
import javax.persistence.metamodel.StaticMetamodel;

@StaticMetamodel(Customer.class)
public abstract class Customer_ {

    // Raw attributes
    public static volatile SingularAttribute<Customer, Integer> id;
    public static volatile SingularAttribute<Customer, String> companyName;
    public static volatile SingularAttribute<Customer, byte[]> contractBinary;
    public static volatile SingularAttribute<Customer, String> contractFileName;
    public static volatile SingularAttribute<Customer, String> contractContentType;
    public static volatile SingularAttribute<Customer, Integer> contractSize;
    public static volatile SingularAttribute<Customer, Integer> version;

    // Many to one
    public static volatile SingularAttribute<Customer, Address> address;

    // One to many
    public static volatile ListAttribute<Customer, Account> accounts;
}