/*
 * Source code generated by Celerio, a Jaxio product.
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Follow us on twitter: @jaxiosoft
 * Need commercial support ? Contact us: info@jaxio.com
 * Template pack-backend-jpa:src/main/java/domain/EntityMeta_.e.vm.java
 * Template is part of Open Source Project: https://github.com/jaxio/pack-backend-jpa
 */
package com.jaxio.jsf2_spring_conversation_bank.domain;

import javax.persistence.metamodel.SingularAttribute;
import javax.persistence.metamodel.StaticMetamodel;

@StaticMetamodel(SavedSearch.class)
public abstract class SavedSearch_ {

    // Raw attributes
    public static volatile SingularAttribute<SavedSearch, Integer> id;
    public static volatile SingularAttribute<SavedSearch, String> name;
    public static volatile SingularAttribute<SavedSearch, String> formClassname;
    public static volatile SingularAttribute<SavedSearch, byte[]> formContent;

    // Many to one
    public static volatile SingularAttribute<SavedSearch, User> user;
}