/*
 * Source code generated by Celerio, a Jaxio product.
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Follow us on twitter: @jaxiosoft
 * Need commercial support ? Contact us: info@jaxio.com
 * Template pack-javaee7-backend:src/main/java/repository/Repository.e.vm.java
 * Template is part of Open Source Project: https://github.com/jaxio/javaee-lab
 */
package com.jaxio.javaee7_wildfly_bank.repository;

import javax.enterprise.context.ApplicationScoped;
import javax.inject.Named;

import com.jaxio.javaee7_wildfly_bank.domain.Currency;
import com.jaxio.jpa.querybyexample.GenericRepository;

/**
 * {@link GenericRepository} for {@link Currency} 
 */
@ApplicationScoped
@Named
public class CurrencyRepository extends GenericRepository<Currency, Integer> {

    public CurrencyRepository() {
        super(Currency.class, Integer::valueOf);
    }

    @Override
    public Currency getNew() {
        return new Currency();
    }

    @Override
    public Currency getNewWithDefaults() {
        return getNew().withDefaults();
    }
}