/*
 * Source code generated by Celerio, a Jaxio product.
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Follow us on twitter: @jaxiosoft
 * Need commercial support ? Contact us: info@jaxio.com
 * Template pack-javaee7-backend:src/main/java/repository/Repository.e.vm.java
 * Template is part of Open Source Project: https://github.com/jaxio/javaee-lab
 */
package com.jaxio.javaee7_wildfly_bank.repository;

import javax.enterprise.context.ApplicationScoped;
import javax.inject.Named;

import org.hibernate.LazyInitializationException;

import com.jaxio.javaee7_wildfly_bank.domain.SavedSearch;
import com.jaxio.jpa.querybyexample.GenericRepository;

/**
 * {@link GenericRepository} for {@link SavedSearch} 
 */
@ApplicationScoped
@Named
public class SavedSearchRepository extends GenericRepository<SavedSearch, Integer> {

    public SavedSearchRepository() {
        super(SavedSearch.class, Integer::valueOf);
    }

    @Override
    public SavedSearch getNew() {
        return new SavedSearch();
    }

    @Override
    public SavedSearch getNewWithDefaults() {
        return getNew().withDefaults();
    }

    /**
     * Safe way to load the formContent content. 
     */
    public byte[] getFormContent(SavedSearch savedSearch) {
        if (!savedSearch.isIdSet()) {
            return savedSearch.getFormContent();
        }

        try {
            return savedSearch.getFormContent();
        } catch (LazyInitializationException lie) { // _HACK_ as we still rely on hibernate here
            return get(savedSearch).getFormContent();
        }
    }
}