/*
 * Source code generated by Celerio, a Jaxio product.
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Follow us on twitter: @jaxiosoft
 * Need commercial support ? Contact us: info@jaxio.com
 * Template pack-javaee7-backend:src/main/java/repository/Repository.e.vm.java
 * Template is part of Open Source Project: https://github.com/jaxio/javaee-lab
 */
package com.jaxio.javaee7_wildfly_bank.repository;

import javax.enterprise.context.ApplicationScoped;
import javax.inject.Named;

import com.jaxio.javaee7_wildfly_bank.domain.Transaction;
import com.jaxio.jpa.querybyexample.GenericRepository;

/**
 * {@link GenericRepository} for {@link Transaction} 
 */
@ApplicationScoped
@Named
public class TransactionRepository extends GenericRepository<Transaction, Integer> {

    public TransactionRepository() {
        super(Transaction.class, Integer::valueOf);
    }

    @Override
    public Transaction getNew() {
        return new Transaction();
    }

    @Override
    public Transaction getNewWithDefaults() {
        return getNew().withDefaults();
    }
}