/*
 * Source code generated by Celerio, a Jaxio product.
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Follow us on twitter: @jaxiosoft
 * Need commercial support ? Contact us: info@jaxio.com
 * Template pack-javaee7-backend:src/main/java/context/UserWithId.p.vm.java
 * Template is part of Open Source Project: https://github.com/jaxio/javaee-lab
 */
package com.jaxio.javaee7_wildfly_bank.context;

import java.io.Serializable;

/**
 * Simple User that also keep track of the primary key.
 */
public class UserWithId implements Serializable {
    private static final long serialVersionUID = 1L;
    private Integer id;
    private final String username;
    private final boolean enabled;

    public UserWithId(String username, boolean enabled, Integer id) {
        this.username = username;
        this.enabled = enabled;
        this.id = id;
    }

    public Integer getId() {
        return id;
    }

    public String getUsername() {
        return username;
    }

    public boolean isEnabled() {
        return enabled;
    }
}