/*
 * Source code generated by Celerio, a Jaxio product.
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Follow us on twitter: @jaxiosoft
 * Need commercial support ? Contact us: info@jaxio.com
 * Template pack-javaee7-backend:src/main/java/printer/Printer.e.vm.java
 * Template is part of Open Source Project: https://github.com/jaxio/javaee-lab
 */
package com.jaxio.javaee7_wildfly_bank.printer;

import java.util.Locale;

import javax.annotation.PostConstruct;
import javax.enterprise.context.ApplicationScoped;
import javax.inject.Named;

import com.jaxio.javaee7_wildfly_bank.domain.Account;
import com.jaxio.javaee7_wildfly_bank.domain.Account_;
import com.jaxio.javaee7_wildfly_bank.printer.support.GenericPrinter;

/**
 * {@link GenericPrinter} for {@link Account} 
 *
 * @see GenericPrinter
 * @see TypeAwarePrinter
 */
@ApplicationScoped
@Named
public class AccountPrinter extends GenericPrinter<Account> {
    @PostConstruct
    public void init() {
        init(Account.class, Account_.accountNumber, Account_.name);
    }

    @Override
    public String print(Account account, Locale locale) {
        if (account == null) {
            return "";
        }
        StringBuilder ret = new StringBuilder();
        appendIfNotEmpty(ret, account.getAccountNumber());
        appendIfNotEmpty(ret, account.getName());
        return ret.toString();
    }
}