/*
 * Source code generated by Celerio, a Jaxio product.
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Follow us on twitter: @jaxiosoft
 * Need commercial support ? Contact us: info@jaxio.com
 * Template pack-javaee7-backend:src/main/java/printer/Printer.e.vm.java
 * Template is part of Open Source Project: https://github.com/jaxio/javaee-lab
 */
package com.jaxio.javaee7_wildfly_bank.printer;

import java.util.Locale;

import javax.annotation.PostConstruct;
import javax.enterprise.context.ApplicationScoped;
import javax.inject.Named;

import com.jaxio.javaee7_wildfly_bank.domain.Address;
import com.jaxio.javaee7_wildfly_bank.domain.Address_;
import com.jaxio.javaee7_wildfly_bank.printer.support.GenericPrinter;

/**
 * {@link GenericPrinter} for {@link Address} 
 *
 * @see GenericPrinter
 * @see TypeAwarePrinter
 */
@ApplicationScoped
@Named
public class AddressPrinter extends GenericPrinter<Address> {
    @PostConstruct
    public void init() {
        init(Address.class, Address_.city, Address_.country);
    }

    @Override
    public String print(Address address, Locale locale) {
        if (address == null) {
            return "";
        }
        StringBuilder ret = new StringBuilder();
        appendIfNotEmpty(ret, address.getCity());
        appendIfNotEmpty(ret, address.getCountry());
        return ret.toString();
    }
}