/*
 * Source code generated by Celerio, a Jaxio product.
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Follow us on twitter: @jaxiosoft
 * Need commercial support ? Contact us: info@jaxio.com
 * Template pack-javaee7-backend:src/main/java/printer/Printer.e.vm.java
 * Template is part of Open Source Project: https://github.com/jaxio/javaee-lab
 */
package com.jaxio.javaee7_wildfly_bank.printer;

import java.util.Locale;

import javax.annotation.PostConstruct;
import javax.enterprise.context.ApplicationScoped;
import javax.inject.Named;

import com.jaxio.javaee7_wildfly_bank.domain.User;
import com.jaxio.javaee7_wildfly_bank.domain.User_;
import com.jaxio.javaee7_wildfly_bank.printer.support.GenericPrinter;

/**
 * {@link GenericPrinter} for {@link User} 
 *
 * @see GenericPrinter
 * @see TypeAwarePrinter
 */
@ApplicationScoped
@Named
public class UserPrinter extends GenericPrinter<User> {
    @PostConstruct
    public void init() {
        init(User.class, User_.username, User_.firstName, User_.lastName);
    }

    @Override
    public String print(User user, Locale locale) {
        if (user == null) {
            return "";
        }
        StringBuilder ret = new StringBuilder();
        appendIfNotEmpty(ret, user.getUsername());
        appendIfNotEmpty(ret, user.getFirstName());
        appendIfNotEmpty(ret, user.getLastName());
        return ret.toString();
    }
}