/*
 * Source code generated by Celerio, a Jaxio product.
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Follow us on twitter: @jaxiosoft
 * Need commercial support ? Contact us: info@jaxio.com
 * Template pack-javaee7-frontend:src/main/java/domain/ExcelExporter.e.vm.java
 * Template is part of Open Source Project: https://github.com/jaxio/javaee-lab
 */
package com.jaxio.javaee7_wildfly_bank.web.domain;

import static org.apache.commons.lang.StringUtils.join;

import javax.faces.view.ViewScoped;
import javax.inject.Inject;
import javax.inject.Named;

import com.jaxio.javaee7_wildfly_bank.domain.Address;
import com.jaxio.javaee7_wildfly_bank.web.domain.support.GenericExcelExporter;

/**
 * Exports to excel document {@link Address} search criteria and result. 
 */
@ViewScoped
@Named
public class AddressExcelExporter extends GenericExcelExporter<Address> {
    private static final long serialVersionUID = 1L;

    @Inject
    protected transient AddressSearchForm sf;

    public AddressExcelExporter() {
        super("address_street", "address_zipCode", "address_city", "address_country");
    }

    @Override
    protected void fillResultItem(int row, Address item) {
        int col = 0;
        setValue(row, col++, item.getStreet());
        setValue(row, col++, item.getZipCode());
        setValue(row, col++, item.getCity());
        setValue(row, col++, item.getCountry());
    }

    @Override
    public void fillSearchCriteria(int row) {
        useCriteriaSheet();
        setLeftHeader(row, 0, "search_full_text");
        setValue(row++, 1, join(sf.getTermsOnAll().getSelected(), ' '));
        setTermSelector(row++, 0, "address_city", sf.getCityTermSelector());
        setTermSelector(row++, 0, "address_country", sf.getCountryTermSelector());

        setSelector(row++, 0, "address_street", sf.getStreetSelector());
        setSelector(row++, 0, "address_zipCode", sf.getZipCodeSelector());
        setSelector(row++, 0, "address_city", sf.getCitySelector());
        setSelector(row++, 0, "address_country", sf.getCountrySelector());
    }
}