/*
 * Source code generated by Celerio, a Jaxio product.
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Follow us on twitter: @jaxiosoft
 * Need commercial support ? Contact us: info@jaxio.com
 * Template pack-javaee7-frontend:src/main/java/domain/Controller.e.vm.java
 * Template is part of Open Source Project: https://github.com/jaxio/javaee-lab
 */
package com.jaxio.javaee7_wildfly_bank.web.domain;

import javax.annotation.PostConstruct;
import javax.enterprise.context.ApplicationScoped;
import javax.inject.Inject;
import javax.inject.Named;

import com.jaxio.javaee7_wildfly_bank.domain.Address;
import com.jaxio.javaee7_wildfly_bank.printer.AddressPrinter;
import com.jaxio.javaee7_wildfly_bank.repository.AddressRepository;
import com.jaxio.javaee7_wildfly_bank.web.domain.support.GenericController;
import com.jaxio.javaee7_wildfly_bank.web.permission.AddressPermission;

/**
 * Stateless controller for {@link Address}. 
 */
@ApplicationScoped
@Named
public class AddressController extends GenericController<Address, Integer> {
    public static final String ADDRESS_EDIT_URI = "/domain/addressEdit.faces";
    public static final String ADDRESS_SELECT_URI = "/domain/addressSelect.faces";

    @Inject
    protected AddressRepository addressRepository;
    @Inject
    protected AddressPermission addressPermission;
    @Inject
    protected AddressPrinter addressPrinter;

    @PostConstruct
    public void init() {
        init(addressRepository, addressPermission, addressPrinter, ADDRESS_SELECT_URI, ADDRESS_EDIT_URI);
    }
}