/*
 * Source code generated by Celerio, a Jaxio product.
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Follow us on twitter: @jaxiosoft
 * Need commercial support ? Contact us: info@jaxio.com
 * Template pack-javaee7-frontend:src/main/java/selectitem.enum.vm.java
 * Template is part of Open Source Project: https://github.com/jaxio/javaee-lab
 */
package com.jaxio.javaee7_wildfly_bank.web.domain;

import static com.google.common.collect.Lists.newArrayList;

import java.util.List;

import javax.enterprise.context.ApplicationScoped;
import javax.faces.model.SelectItem;
import javax.inject.Named;

import com.jaxio.javaee7_wildfly_bank.domain.Civility;

/**
 * Helper to support the <code>h:selectOneRadio</code> and <code>h:selectOneMenu</code> for {@link Civility}
 */
@ApplicationScoped
@Named
public class CivilityItems {

    /**
     * Returns a list of {@link SelectItem}/{@link Civility} ready to use in a <code>h:selectOneRadio</code>, <code>h:selectOneMenu</code> or <code>p:selectManyCheckbox</code> tags
     */
    public List<SelectItem> getList() {
        List<SelectItem> result = newArrayList();
        for (Civility civility : Civility.values()) {
            result.add(new SelectItem(civility, civility.getLabel()));
        }

        return result;
    }
}
