/*
 * Source code generated by Celerio, a Jaxio product.
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Follow us on twitter: @jaxiosoft
 * Need commercial support ? Contact us: info@jaxio.com
 * Template pack-javaee7-frontend:src/main/java/domain/ExcelExporter.e.vm.java
 * Template is part of Open Source Project: https://github.com/jaxio/javaee-lab
 */
package com.jaxio.javaee7_wildfly_bank.web.domain;

import javax.faces.view.ViewScoped;
import javax.inject.Inject;
import javax.inject.Named;

import com.jaxio.javaee7_wildfly_bank.domain.Currency;
import com.jaxio.javaee7_wildfly_bank.web.domain.support.GenericExcelExporter;

/**
 * Exports to excel document {@link Currency} search criteria and result. 
 */
@ViewScoped
@Named
public class CurrencyExcelExporter extends GenericExcelExporter<Currency> {
    private static final long serialVersionUID = 1L;

    @Inject
    protected transient CurrencySearchForm sf;

    public CurrencyExcelExporter() {
        super("currency_code", "currency_name", "currency_decimalCount");
    }

    @Override
    protected void fillResultItem(int row, Currency item) {
        int col = 0;
        setValue(row, col++, item.getCode());
        setValue(row, col++, item.getName());
        setValue(row, col++, item.getDecimalCount());
    }

    @Override
    public void fillSearchCriteria(int row) {
        useCriteriaSheet();

        setSelector(row++, 0, "currency_code", sf.getCodeSelector());
        setSelector(row++, 0, "currency_name", sf.getNameSelector());
        setRangeNumber(row++, 0, "currency_decimalCount", sf.getDecimalCountRange());
    }
}