/*
 * Source code generated by Celerio, a Jaxio product.
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Follow us on twitter: @jaxiosoft
 * Need commercial support ? Contact us: info@jaxio.com
 * Template pack-javaee7-frontend:src/main/java/domain/LazyDataModel.e.vm.java
 * Template is part of Open Source Project: https://github.com/jaxio/javaee-lab
 */
package com.jaxio.javaee7_wildfly_bank.web.domain;

import javax.faces.view.ViewScoped;
import javax.inject.Inject;
import javax.inject.Named;

import org.primefaces.model.LazyDataModel;

import com.jaxio.javaee7_wildfly_bank.domain.Currency;
import com.jaxio.javaee7_wildfly_bank.repository.CurrencyRepository;
import com.jaxio.javaee7_wildfly_bank.web.domain.support.GenericLazyDataModel;

/**
 * Provide PrimeFaces {@link LazyDataModel} for {@link Currency}
 */
@ViewScoped
@Named
public class CurrencyLazyDataModel extends GenericLazyDataModel<Currency, Integer, CurrencySearchForm> {
    private static final long serialVersionUID = 1L;

    public CurrencyLazyDataModel() {
        // mandatory no-args constructor to make this bean proxyable
    }

    @Inject
    public CurrencyLazyDataModel(CurrencyRepository currencyRepository, CurrencyController currencyController, CurrencySearchForm currencySearchForm,
            CurrencyExcelExporter currencyExcelExporter) {
        super(currencyRepository, currencyController, currencySearchForm, currencyExcelExporter);
    }
}