/*
 * Source code generated by Celerio, a Jaxio product.
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Follow us on twitter: @jaxiosoft
 * Need commercial support ? Contact us: info@jaxio.com
 * Template pack-javaee7-frontend:src/main/java/domain/Controller.e.vm.java
 * Template is part of Open Source Project: https://github.com/jaxio/javaee-lab
 */
package com.jaxio.javaee7_wildfly_bank.web.domain;

import javax.annotation.PostConstruct;
import javax.enterprise.context.ApplicationScoped;
import javax.inject.Inject;
import javax.inject.Named;

import com.jaxio.javaee7_wildfly_bank.domain.Customer;
import com.jaxio.javaee7_wildfly_bank.printer.CustomerPrinter;
import com.jaxio.javaee7_wildfly_bank.repository.CustomerRepository;
import com.jaxio.javaee7_wildfly_bank.web.domain.support.GenericController;
import com.jaxio.javaee7_wildfly_bank.web.permission.CustomerPermission;

/**
 * Stateless controller for {@link Customer}. 
 */
@ApplicationScoped
@Named
public class CustomerController extends GenericController<Customer, Integer> {
    public static final String CUSTOMER_EDIT_URI = "/domain/customerEdit.faces";
    public static final String CUSTOMER_SELECT_URI = "/domain/customerSelect.faces";

    @Inject
    protected CustomerRepository customerRepository;
    @Inject
    protected CustomerPermission customerPermission;
    @Inject
    protected CustomerPrinter customerPrinter;

    @PostConstruct
    public void init() {
        init(customerRepository, customerPermission, customerPrinter, CUSTOMER_SELECT_URI, CUSTOMER_EDIT_URI);
    }

    public CustomerFileUpload getCustomerFileUpload(Customer customer) {
        return new CustomerFileUpload(customer);
    }
}