/*
 * Source code generated by Celerio, a Jaxio product.
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Follow us on twitter: @jaxiosoft
 * Need commercial support ? Contact us: info@jaxio.com
 * Template pack-javaee7-frontend:src/main/java/domain/ExcelExporter.e.vm.java
 * Template is part of Open Source Project: https://github.com/jaxio/javaee-lab
 */
package com.jaxio.javaee7_wildfly_bank.web.domain;

import javax.faces.view.ViewScoped;
import javax.inject.Inject;
import javax.inject.Named;

import com.jaxio.javaee7_wildfly_bank.domain.Customer;
import com.jaxio.javaee7_wildfly_bank.web.domain.support.GenericExcelExporter;

/**
 * Exports to excel document {@link Customer} search criteria and result. 
 */
@ViewScoped
@Named
public class CustomerExcelExporter extends GenericExcelExporter<Customer> {
    private static final long serialVersionUID = 1L;

    @Inject
    protected transient CustomerSearchForm sf;

    public CustomerExcelExporter() {
        super("customer_companyName", "customer_contractFileName");
    }

    @Override
    protected void fillResultItem(int row, Customer item) {
        int col = 0;
        setValue(row, col++, item.getCompanyName());
        setValue(row, col++, item.getContractFileName());
    }

    @Override
    public void fillSearchCriteria(int row) {
        useCriteriaSheet();

        setSelector(row++, 0, "customer_companyName", sf.getCompanyNameSelector());
        setSelectedEntities(row++, 0, "customer_address", sf.getAddressSelector().getSelected());
    }
}