/*
 * Source code generated by Celerio, a Jaxio product.
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Follow us on twitter: @jaxiosoft
 * Need commercial support ? Contact us: info@jaxio.com
 * Template pack-javaee7-frontend:src/main/java/domain/EditForm.e.vm.java
 * Template is part of Open Source Project: https://github.com/jaxio/javaee-lab
 */
package com.jaxio.javaee7_wildfly_bank.web.domain;

import javax.faces.view.ViewScoped;
import javax.inject.Inject;
import javax.inject.Named;

import com.jaxio.javaee7_wildfly_bank.domain.Role;
import com.jaxio.javaee7_wildfly_bank.repository.RoleRepository;
import com.jaxio.javaee7_wildfly_bank.web.domain.support.GenericEditForm;

/**
 * View Helper/Controller to edit {@link Role}.
 */
@ViewScoped
@Named
public class RoleEditForm extends GenericEditForm<Role, Integer> {
    private static final long serialVersionUID = 1L;
    @Inject
    protected transient RoleController roleController;

    public RoleEditForm() {
        // mandatory no-args constructor to make this bean proxyable
    }

    @Inject
    public RoleEditForm(RoleRepository roleRepository) {
        super(roleRepository);
    }

    /**
     * The entity to edit/view.
     */
    public Role getRole() {
        return getEntity();
    }

    public String print() {
        return roleController.print(getRole());
    }
}