/*
 * Source code generated by Celerio, a Jaxio product.
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Follow us on twitter: @jaxiosoft
 * Need commercial support ? Contact us: info@jaxio.com
 * Template pack-javaee7-frontend:src/main/java/domain/ExcelExporter.e.vm.java
 * Template is part of Open Source Project: https://github.com/jaxio/javaee-lab
 */
package com.jaxio.javaee7_wildfly_bank.web.domain;

import javax.faces.view.ViewScoped;
import javax.inject.Inject;
import javax.inject.Named;

import com.jaxio.javaee7_wildfly_bank.domain.Role;
import com.jaxio.javaee7_wildfly_bank.web.domain.support.GenericExcelExporter;

/**
 * Exports to excel document {@link Role} search criteria and result. 
 */
@ViewScoped
@Named
public class RoleExcelExporter extends GenericExcelExporter<Role> {
    private static final long serialVersionUID = 1L;

    @Inject
    protected transient RoleSearchForm sf;

    public RoleExcelExporter() {
        super("role_roleName");
    }

    @Override
    protected void fillResultItem(int row, Role item) {
        int col = 0;
        setValue(row, col++, item.getRoleName());
    }

    @Override
    public void fillSearchCriteria(int row) {
        useCriteriaSheet();
        setTermSelector(row++, 0, "role_roleName", sf.getRoleNameTermSelector());

        setSelector(row++, 0, "role_roleName", sf.getRoleNameSelector());
    }
}