/*
 * Source code generated by Celerio, a Jaxio product.
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Follow us on twitter: @jaxiosoft
 * Need commercial support ? Contact us: info@jaxio.com
 * Template pack-javaee7-frontend:src/main/java/domain/Controller.e.vm.java
 * Template is part of Open Source Project: https://github.com/jaxio/javaee-lab
 */
package com.jaxio.javaee7_wildfly_bank.web.domain;

import javax.annotation.PostConstruct;
import javax.enterprise.context.ApplicationScoped;
import javax.inject.Inject;
import javax.inject.Named;

import com.jaxio.javaee7_wildfly_bank.domain.Role;
import com.jaxio.javaee7_wildfly_bank.domain.Role_;
import com.jaxio.javaee7_wildfly_bank.printer.RolePrinter;
import com.jaxio.javaee7_wildfly_bank.repository.RoleRepository;
import com.jaxio.javaee7_wildfly_bank.web.domain.support.GenericController;
import com.jaxio.javaee7_wildfly_bank.web.permission.RolePermission;
import com.jaxio.jpa.querybyexample.SearchParameters;

/**
 * Stateless controller for {@link Role}. 
 */
@ApplicationScoped
@Named
public class RoleController extends GenericController<Role, Integer> {
    public static final String ROLE_EDIT_URI = "/domain/roleEdit.faces";
    public static final String ROLE_SELECT_URI = "/domain/roleSelect.faces";

    @Inject
    protected RoleRepository roleRepository;
    @Inject
    protected RolePermission rolePermission;
    @Inject
    protected RolePrinter rolePrinter;

    @PostConstruct
    public void init() {
        init(roleRepository, rolePermission, rolePrinter, ROLE_SELECT_URI, ROLE_EDIT_URI);
    }

    @Override
    protected SearchParameters defaultOrder(SearchParameters searchParameters) {
        return searchParameters.asc(Role_.roleName);
    }
}