/*
 * Source code generated by Celerio, a Jaxio product.
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Follow us on twitter: @jaxiosoft
 * Need commercial support ? Contact us: info@jaxio.com
 * Template pack-javaee7-frontend:src/main/java/domain/FileUpload.e.vm.java
 * Template is part of Open Source Project: https://github.com/jaxio/javaee-lab
 */
package com.jaxio.javaee7_wildfly_bank.web.domain;

import org.primefaces.event.FileUploadEvent;
import org.primefaces.model.UploadedFile;

import com.jaxio.javaee7_wildfly_bank.domain.SavedSearch;

public class SavedSearchFileUpload {
    private SavedSearch savedSearch;

    public SavedSearchFileUpload(SavedSearch savedSearch) {
        this.savedSearch = savedSearch;
    }

    /**
     * Primefaces support for formContent file upload
     */
    public void onFormContentFileUpload(FileUploadEvent fileUploadEvent) {
        UploadedFile uploadedFile = fileUploadEvent.getFile(); //application code
        savedSearch.setFormContent(uploadedFile.getContents());
    }
}