/*
 * Source code generated by Celerio, a Jaxio product.
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Follow us on twitter: @jaxiosoft
 * Need commercial support ? Contact us: info@jaxio.com
 * Template pack-javaee7-frontend:src/main/java/domain/Controller.e.vm.java
 * Template is part of Open Source Project: https://github.com/jaxio/javaee-lab
 */
package com.jaxio.javaee7_wildfly_bank.web.domain;

import javax.annotation.PostConstruct;
import javax.enterprise.context.ApplicationScoped;
import javax.inject.Inject;
import javax.inject.Named;

import com.jaxio.javaee7_wildfly_bank.domain.SavedSearch;
import com.jaxio.javaee7_wildfly_bank.printer.SavedSearchPrinter;
import com.jaxio.javaee7_wildfly_bank.repository.SavedSearchRepository;
import com.jaxio.javaee7_wildfly_bank.web.domain.support.GenericController;
import com.jaxio.javaee7_wildfly_bank.web.permission.SavedSearchPermission;

/**
 * Stateless controller for {@link SavedSearch}. 
 */
@ApplicationScoped
@Named
public class SavedSearchController extends GenericController<SavedSearch, Integer> {
    public static final String SAVEDSEARCH_EDIT_URI = "/domain/savedSearchEdit.faces";
    public static final String SAVEDSEARCH_SELECT_URI = "/domain/savedSearchSelect.faces";

    @Inject
    protected SavedSearchRepository savedSearchRepository;
    @Inject
    protected SavedSearchPermission savedSearchPermission;
    @Inject
    protected SavedSearchPrinter savedSearchPrinter;

    @PostConstruct
    public void init() {
        init(savedSearchRepository, savedSearchPermission, savedSearchPrinter, SAVEDSEARCH_SELECT_URI, SAVEDSEARCH_EDIT_URI);
    }

    public SavedSearchFileUpload getSavedSearchFileUpload(SavedSearch savedSearch) {
        return new SavedSearchFileUpload(savedSearch);
    }
}