/*
 * Source code generated by Celerio, a Jaxio product.
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Follow us on twitter: @jaxiosoft
 * Need commercial support ? Contact us: info@jaxio.com
 * Template pack-javaee7-frontend:src/main/java/domain/ExcelExporter.e.vm.java
 * Template is part of Open Source Project: https://github.com/jaxio/javaee-lab
 */
package com.jaxio.javaee7_wildfly_bank.web.domain;

import javax.faces.view.ViewScoped;
import javax.inject.Inject;
import javax.inject.Named;

import com.jaxio.javaee7_wildfly_bank.domain.Transaction;
import com.jaxio.javaee7_wildfly_bank.web.domain.support.GenericExcelExporter;

/**
 * Exports to excel document {@link Transaction} search criteria and result. 
 */
@ViewScoped
@Named
public class TransactionExcelExporter extends GenericExcelExporter<Transaction> {
    private static final long serialVersionUID = 1L;

    @Inject
    protected transient TransactionSearchForm sf;

    public TransactionExcelExporter() {
        super("transaction_account", "transaction_amount", "transaction_transactionDate", "transaction_valueDate", "transaction_description");
    }

    @Override
    protected void fillResultItem(int row, Transaction item) {
        int col = 0;
        setEntity(row, col++, item.getAccount());
        setValue(row, col++, item.getAmount());
        setValue(row, col++, item.getTransactionDate());
        setValue(row, col++, item.getValueDate());
        setValue(row, col++, item.getDescription());
    }

    @Override
    public void fillSearchCriteria(int row) {
        useCriteriaSheet();

        setSelectedEntities(row++, 0, "transaction_account", sf.getAccountSelector().getSelected());
        setRangeNumber(row++, 0, "transaction_amount", sf.getAmountRange());
        setRangeDate(row++, 0, "transaction_transactionDate", sf.getTransactionDateRange());
        setRangeDate(row++, 0, "transaction_valueDate", sf.getValueDateRange());
        setSelectedEntities(row++, 0, "transaction_currency", sf.getCurrencySelector().getSelected());
        setSelector(row++, 0, "transaction_description", sf.getDescriptionSelector());
    }
}