/*
 * Source code generated by Celerio, a Jaxio product.
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Follow us on twitter: @jaxiosoft
 * Need commercial support ? Contact us: info@jaxio.com
 * Template pack-javaee7-frontend:src/main/java/domain/Controller.e.vm.java
 * Template is part of Open Source Project: https://github.com/jaxio/javaee-lab
 */
package com.jaxio.javaee7_wildfly_bank.web.domain;

import javax.annotation.PostConstruct;
import javax.enterprise.context.ApplicationScoped;
import javax.inject.Inject;
import javax.inject.Named;

import com.jaxio.javaee7_wildfly_bank.domain.Transaction;
import com.jaxio.javaee7_wildfly_bank.printer.TransactionPrinter;
import com.jaxio.javaee7_wildfly_bank.repository.TransactionRepository;
import com.jaxio.javaee7_wildfly_bank.web.domain.support.GenericController;
import com.jaxio.javaee7_wildfly_bank.web.permission.TransactionPermission;

/**
 * Stateless controller for {@link Transaction}. 
 */
@ApplicationScoped
@Named
public class TransactionController extends GenericController<Transaction, Integer> {
    public static final String TRANSACTION_EDIT_URI = "/domain/transactionEdit.faces";
    public static final String TRANSACTION_SELECT_URI = "/domain/transactionSelect.faces";

    @Inject
    protected TransactionRepository transactionRepository;
    @Inject
    protected TransactionPermission transactionPermission;
    @Inject
    protected TransactionPrinter transactionPrinter;

    @PostConstruct
    public void init() {
        init(transactionRepository, transactionPermission, transactionPrinter, TRANSACTION_SELECT_URI, TRANSACTION_EDIT_URI);
    }
}