/*
 * Source code generated by Celerio, a Jaxio product.
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Follow us on twitter: @jaxiosoft
 * Need commercial support ? Contact us: info@jaxio.com
 * Template pack-javaee7-frontend:src/main/java/domain/GraphLoader.e.vm.java
 * Template is part of Open Source Project: https://github.com/jaxio/javaee-lab
 */
package com.jaxio.javaee7_wildfly_bank.web.domain;

import static javax.ejb.TransactionManagementType.BEAN;

import javax.ejb.Singleton;
import javax.ejb.TransactionManagement;
import javax.inject.Inject;
import javax.inject.Named;

import com.jaxio.javaee7_wildfly_bank.domain.Transaction;
import com.jaxio.javaee7_wildfly_bank.repository.TransactionRepository;
import com.jaxio.jpa.querybyexample.EntityGraphLoader;

/**
 * Preloads the {@link Transaction} associations required by the view layer.
 * Do not use other GraphLoaders in this GraphLoader. 
 */
@TransactionManagement(BEAN)
@Singleton
@Named
public class TransactionGraphLoader extends EntityGraphLoader<Transaction, Integer> {

    public TransactionGraphLoader() {
        // required no-args construct to make this bean is proxyable
    }

    @Inject
    public TransactionGraphLoader(TransactionRepository transactionRepository) {
        super(transactionRepository);
    }

    @Override
    public void loadGraph(Transaction transaction) {
        loadSingular(transaction.getCurrency());
        loadSingular(transaction.getAccount());
    }
}