/*
 * Source code generated by Celerio, a Jaxio product.
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Follow us on twitter: @jaxiosoft
 * Need commercial support ? Contact us: info@jaxio.com
 * Template pack-javaee7-frontend:src/main/java/domain/Controller.e.vm.java
 * Template is part of Open Source Project: https://github.com/jaxio/javaee-lab
 */
package com.jaxio.javaee7_wildfly_bank.web.domain;

import javax.annotation.PostConstruct;
import javax.enterprise.context.ApplicationScoped;
import javax.inject.Inject;
import javax.inject.Named;

import com.jaxio.javaee7_wildfly_bank.domain.User;
import com.jaxio.javaee7_wildfly_bank.domain.User_;
import com.jaxio.javaee7_wildfly_bank.printer.UserPrinter;
import com.jaxio.javaee7_wildfly_bank.repository.UserRepository;
import com.jaxio.javaee7_wildfly_bank.web.domain.support.GenericController;
import com.jaxio.javaee7_wildfly_bank.web.permission.UserPermission;
import com.jaxio.jpa.querybyexample.SearchParameters;

/**
 * Stateless controller for {@link User}. 
 */
@ApplicationScoped
@Named
public class UserController extends GenericController<User, Integer> {
    public static final String USER_EDIT_URI = "/domain/userEdit.faces";
    public static final String USER_SELECT_URI = "/domain/userSelect.faces";

    @Inject
    protected UserRepository userRepository;
    @Inject
    protected UserPermission userPermission;
    @Inject
    protected UserPrinter userPrinter;

    @PostConstruct
    public void init() {
        init(userRepository, userPermission, userPrinter, USER_SELECT_URI, USER_EDIT_URI);
    }

    @Override
    protected SearchParameters defaultOrder(SearchParameters searchParameters) {
        return searchParameters.asc(User_.username);
    }
}