/*
 * Source code generated by Celerio, a Jaxio product.
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Follow us on twitter: @jaxiosoft
 * Need commercial support ? Contact us: info@jaxio.com
 * Template pack-javaee7-frontend:src/main/java/domain/EditForm.e.vm.java
 * Template is part of Open Source Project: https://github.com/jaxio/javaee-lab
 */
package com.jaxio.javaee7_wildfly_bank.web.domain;

import javax.faces.view.ViewScoped;
import javax.inject.Inject;
import javax.inject.Named;

import com.jaxio.javaee7_wildfly_bank.domain.Role;
import com.jaxio.javaee7_wildfly_bank.domain.User;
import com.jaxio.javaee7_wildfly_bank.repository.UserRepository;
import com.jaxio.javaee7_wildfly_bank.web.domain.support.GenericEditForm;
import com.jaxio.javaee7_wildfly_bank.web.domain.support.GenericToManyAssociation;
import com.jaxio.javaee7_wildfly_bank.web.util.TabBean;

/**
 * View Helper/Controller to edit {@link User}.
 */
@ViewScoped
@Named
public class UserEditForm extends GenericEditForm<User, Integer> {
    private static final long serialVersionUID = 1L;
    @Inject
    protected transient UserController userController;
    @Inject
    protected transient RoleController roleController;
    protected transient GenericToManyAssociation<Role, Integer> securityRoles;
    protected TabBean tabBean = new TabBean();

    public UserEditForm() {
        // mandatory no-args constructor to make this bean proxyable
    }

    @Inject
    public UserEditForm(UserRepository userRepository, UserGraphLoader userGraphLoader) {
        super(userRepository, userGraphLoader);
    }

    /**
     * View helper to store the x-to-many associations tab's index. 
     */
    @Override
    public TabBean getTabBean() {
        return tabBean;
    }

    /**
     * The entity to edit/view.
     */
    public User getUser() {
        return getEntity();
    }

    @Override
    protected void onInit() {
        setupSecurityRolesActions();
    }

    public String print() {
        return userController.print(getUser());
    }

    void setupSecurityRolesActions() {
        securityRoles = new GenericToManyAssociation<Role, Integer>(getUser().getSecurityRoles(), "user_securityRoles", roleController) {
            @Override
            protected void remove(Role role) {
                getUser().removeSecurityRole(role);
            }

            @Override
            protected void add(Role role) {
                // add the object only to the securityRole side of the relation 
                getUser().getSecurityRoles().add(role);
            }
        };
    }

    public GenericToManyAssociation<Role, Integer> getSecurityRoles() {
        return securityRoles;
    }
}