/*
 * Source code generated by Celerio, a Jaxio product.
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Follow us on twitter: @jaxiosoft
 * Need commercial support ? Contact us: info@jaxio.com
 * Template pack-javaee7-frontend:src/main/java/domain/ExcelExporter.e.vm.java
 * Template is part of Open Source Project: https://github.com/jaxio/javaee-lab
 */
package com.jaxio.javaee7_wildfly_bank.web.domain;

import static org.apache.commons.lang.StringUtils.join;

import javax.faces.view.ViewScoped;
import javax.inject.Inject;
import javax.inject.Named;

import com.jaxio.javaee7_wildfly_bank.domain.User;
import com.jaxio.javaee7_wildfly_bank.web.domain.support.GenericExcelExporter;

/**
 * Exports to excel document {@link User} search criteria and result. 
 */
@ViewScoped
@Named
public class UserExcelExporter extends GenericExcelExporter<User> {
    private static final long serialVersionUID = 1L;

    @Inject
    protected transient UserSearchForm sf;

    public UserExcelExporter() {
        super("user_username", "user_email", "user_isEnabled");
    }

    @Override
    protected void fillResultItem(int row, User item) {
        int col = 0;
        setValue(row, col++, item.getUsername());
        setValue(row, col++, item.getEmail());
        setValue(row, col++, item.getIsEnabled());
    }

    @Override
    public void fillSearchCriteria(int row) {
        useCriteriaSheet();
        setLeftHeader(row, 0, "search_full_text");
        setValue(row++, 1, join(sf.getTermsOnAll().getSelected(), ' '));
        setTermSelector(row++, 0, "user_email", sf.getEmailTermSelector());
        setTermSelector(row++, 0, "user_firstName", sf.getFirstNameTermSelector());
        setTermSelector(row++, 0, "user_lastName", sf.getLastNameTermSelector());

        setSelector(row++, 0, "user_username", sf.getUsernameSelector());
        setSelector(row++, 0, "user_password", sf.getPasswordSelector());
        setSelector(row++, 0, "user_email", sf.getEmailSelector());
        setSelector(row++, 0, "user_isEnabled", sf.getIsEnabledSelector());
        setSelector(row++, 0, "user_civility", sf.getCivilitySelector());
        setSelector(row++, 0, "user_firstName", sf.getFirstNameSelector());
        setSelector(row++, 0, "user_lastName", sf.getLastNameSelector());
        setSelectedEntities(row++, 0, "user_securityRoles", sf.getUser().getSecurityRoles());
    }
}