/*
 * Source code generated by Celerio, a Jaxio product.
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Follow us on twitter: @jaxiosoft
 * Need commercial support ? Contact us: info@jaxio.com
 * Template pack-javaee7-frontend:src/main/java/security/LoginForm.p.vm.java
 * Template is part of Open Source Project: https://github.com/jaxio/javaee-lab
 */
package com.jaxio.javaee7_wildfly_bank.web.security;

import java.io.IOException;
import java.io.Serializable;
import java.util.logging.Level;
import java.util.logging.Logger;

import javax.faces.context.ExternalContext;
import javax.faces.context.FacesContext;
import javax.faces.view.ViewScoped;
import javax.inject.Inject;
import javax.inject.Named;

import org.apache.shiro.SecurityUtils;
import org.apache.shiro.authc.AuthenticationException;
import org.apache.shiro.authc.UsernamePasswordToken;
import org.apache.shiro.web.util.SavedRequest;
import org.apache.shiro.web.util.WebUtils;
import org.omnifaces.util.Faces;

import com.jaxio.javaee7_wildfly_bank.web.util.MessageUtil;

/**
 * More info on login: http://balusc.blogspot.fr/2013/01/apache-shiro-is-it-ready-for-java-ee-6.html
 */
@Named
@ViewScoped
public class LoginForm implements Serializable {
    public static final String HOME_URL = "/home.faces";

    @Inject
    private transient Logger log;
    @Inject
    private transient MessageUtil messageUtil;

    private String username;
    private String password;
    private boolean rememberMe;

    public void submit() throws IOException {
        try {
            SecurityUtils.getSubject().login(new UsernamePasswordToken(username, password, rememberMe));
            SavedRequest savedRequest = WebUtils.getAndClearSavedRequest(Faces.getRequest());
            ExternalContext externalContext = FacesContext.getCurrentInstance().getExternalContext();
            String redirectUrl = externalContext.getRequestContextPath() + HOME_URL;
            Faces.redirect(savedRequest != null ? savedRequest.getRequestUrl() : redirectUrl);
        } catch (AuthenticationException e) {
            messageUtil.error("login_error");
            log.log(Level.SEVERE, "AuthenticationException for user " + username, e);
        }
    }

    public String getUsername() {
        return username;
    }

    public void setUsername(String username) {
        this.username = username;
    }

    public String getPassword() {
        return password;
    }

    public void setPassword(String password) {
        this.password = password;
    }

    public boolean isRememberMe() {
        return rememberMe;
    }

    public void setRememberMe(boolean rememberMe) {
        this.rememberMe = rememberMe;
    }
}