/*
 * Source code generated by Celerio, a Jaxio product.
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Follow us on twitter: @jaxiosoft
 * Need commercial support ? Contact us: info@jaxio.com
 * Template pack-javaee7-frontend:src/main/java/converter/support/NumberToStringConverter.p.vm.java
 * Template is part of Open Source Project: https://github.com/jaxio/javaee-lab
 */
package com.jaxio.javaee7_wildfly_bank.web.converter.support;

import javax.inject.Named;

import org.apache.commons.lang.math.NumberUtils;

@Named
public class NumberToStringConverter extends AbstractTypeConverter<String, Number> {

    @Override
    public Number convert(String source) {
        return NumberUtils.createNumber(source);
    }

    @Override
    Class<String> getSourceType() {
        return String.class;
    }

    @Override
    Class<Number> getTargetType() {
        return Number.class;
    }
}
